local M = {}

M.spaceo = {
  n = {
    ["<leader>odA"] = {":NvimTreeOpen " .. "/Applications/<CR>", "Open applications directory"},
    ["<leader>odb"] = {":NvimTreeOpen " .. "~/blog/<CR>", "Open blog directory"},
    ["<leader>odB"] = {":NvimTreeOpen " .. "~/bin/<CR>", "Open bin directory"},
    ["<leader>odC"] = {":NvimTreeOpen " .. "~/Cafe/<CR>", "Open cafe directory"},
    ["<leader>odc"] = {":NvimTreeOpen " .. "~/.config/<CR>", "Open config directory"},
    ["<leader>od<C-c>"] = {":NvimTreeOpen " .. "~/cascode/<CR>", "Open cascode directory"},
    ["<leader>odd"] = {":NvimTreeOpen " .. "~/Downloads/<CR>", "Open downloads directory"},
    ["<leader>odD"] = {":NvimTreeOpen " .. "~/Documents/<CR>", "Open documents directory"},
    ["<leader>odf"] = {":NvimTreeOpen " .. "~/.fzf/<CR>", "Open fzf directory"},
    ["<leader>odg"] = {":NvimTreeOpen " .. "~/cascode/github.com/<CR>", "Open github directory"},
    ["<leader>odH"] = {":NvimTreeOpen " .. "/home<CR>", "Open home directory"},
    ["<leader>odh"] = {":NvimTreeOpen " .. "~/<CR>", "Open user directory"},
    ["<leader>odi"] = {":NvimTreeOpen " .. "~/Library/Mobile Documents/com~apple~CloudDocs/<CR>", "Open icloud directory"},
    ["<leader>odk"] = {":NvimTreeOpen " .. "~/kt/<CR>", "Open kt directory"},
    ["<leader>odl"] = {":NvimTreeOpen " .. "~/Library/Application Support/<CR>", "Open las directory"},
    ["<leader>odL"] = {":NvimTreeOpen " .. "~/Library/Preferences/<CR>", "Open lp directory"},
    ["<leader>odM"] = {":NvimTreeOpen " .. "~/Movies/<CR>", "Open movies directory"},
    ["<leader>odm"] = {":NvimTreeOpen " .. "~/Documents/materials/<CR>", "Open materials directory"},
    ["<leader>ods"] = {":NvimTreeOpen " .. "~/Documents/materials/scratches/<CR>", "Open scratch directory"},
    ["<leader>odS"] = {":NvimTreeOpen " .. "~/snips/<CR>", "Open snips directory"},
    ["<leader>od<C-s>"] = {":NvimTreeOpen " .. "~/Documents/materials/snippets<CR>", "Open snippets directory"},
    ["<leader>ode"] = {":NvimTreeOpen " .. "~/.emacs.spacemacs.d<CR>", "Open emacs directory"},
    ["<leader>odz"] = {":NvimTreeOpen " .. "~/.spacezsh/<CR>", "Open spacezsh directory"},
    ["<leader>odZ"] = {":NvimTreeOpen " .. "~/.oh-my-zsh/<CR>", "Open ohmyzsh directory"},
    ["<leader>od/"] = {":NvimTreeOpen " .. "/<CR>", "Open root directory"},
    ["<leader>odo"] = {":NvimTreeOpen " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org<CR>", "Open org directory"},
    ["<leader>odj"] = {":NvimTreeOpen " .. "~/Documents/materials/journal<CR>", "Open journal directory"},
    ["<leader>odJ"] = {":NvimTreeOpen " .. "~/Documents/materials/jira<CR>", "Open jira directory"},
    ["<leader>odn"] = {":NvimTreeOpen " .. "~/Documents/materials/notes<CR>", "Open notes directory"},
    ["<leader>odN"] = {":NvimTreeOpen " .. "~/Documents/evernotes<CR>", "Open evernotes directory"},
    ["<leader>odw"] = {":NvimTreeOpen " .. "~/Documents/materials/webclips<CR>", "Open webclips directory"},
    ["<leader>odv"] = {":NvimTreeOpen " .. "/Volumes<CR>", "Open volumes directory"},
    ["<leader>odT"] = {":NvimTreeOpen " .. "~/.tmux<CR>", "Open tmux directory"},
    ["<leader>odt"] = {":NvimTreeOpen " .. "~/tmp/<CR>", "Open tmp directory"},

    ["<leader>och"] = {":edit " .. "/etc/hosts<CR>", "Open hosts config"},
    ["<leader>ocS"] = {":edit " .. "/etc/sudoers<CR>", "Open sudoers config"},
    ["<leader>ocz"] = {":edit " .. "~/.zshrc<CR>", "Open zshrc config"},
    ["<leader>ocp"] = {":edit " .. "~/.pryrc<CR>", "Open pryrc config"},
    ["<leader>ocl"] = {":edit " .. "~/.vrl.yml<CR>", "Open vrl config"},
    ["<leader>ocg"] = {":edit " .. "~/.gitconfig<CR>", "Open git config"},
    ["<leader>ocd"] = {":edit " .. "~/.docker<CR>", "Open docker config"},
    ["<leader>ocs"] = {":edit " .. "~/.ssh/config<CR>", "Open ssh config"},
    ["<leader>ocA"] = {":edit " .. "~/.ssh/authorized_keys<CR>", "Open authorized_keys config"},
    ["<leader>oca"] = {":edit " .. "/etc/ansible<CR>", "Open ansible config"},
    ["<leader>oct"] = {":edit " .. "~/.tmux.conf<CR>", "Open tmux config"},
    ["<leader>ocJ"] = {":edit " .. "~/.jenkins-builder.yaml<CR>", "Open jenkins-builder config"},
    ["<leader>ocj"] = {":edit " .. "~/.ideavimrc<CR>", "Open ideavimrc config"},
    ["<leader>ocn"] = {":edit " .. "/usr/local/etc/nginx<CR>", "Open nginx config"},
    ["<leader>ock"] = {":edit " .. "~/.kube/config<CR>", "Open kubectl config"},
    ["<leader>ocK"] = {":edit " .. "~/.k9s<CR>", "Open k9s config"},
    ["<leader>oc9"] = {":edit " .. "~/.k9s<CR>", "Open k9s2 config"},
    ["<leader>ocq"] = {":edit " .. "~/.arql.d<CR>", "Open arql config"},
    ["<leader>ocm"] = {":edit " .. "~/.m2/settings.xml<CR>", "Open maven config"},
    ["<leader>ocv"] = {":edit " .. "~/.vimrc<CR>", "Open vimrc config"},

    ["<leader>oea"] = { ":edit " .. "~/Documents/materials/demo/demo.art<CR>", "Open artist-demo"},
    ["<leader>oeb"] = { ":edit " .. "~/Documents/materials/demo/big.txt<CR>", "Open bigtxt-demo"},
    ["<leader>oeh"] = { ":edit " .. "~/Documents/materials/demo/demo-http.org<CR>", "Open http-demo"},
    ["<leader>oel"] = { ":edit " .. "~/Documents/materials/demo/demo.el<CR>", "Open elisp-demo"},
    ["<leader>oer"] = { ":edit " .. "~/Documents/materials/demo/demo.rb<CR>", "Open ruby-demo"},
    ["<leader>oeP"] = { ":edit " .. "~/Documents/materials/demo/demo.py<CR>", "Open python-demo"},
    ["<leader>oeJ"] = { ":edit " .. "~/cascode/java/maven/simple/src/main/java/org/sonatype/mavenbook/App.java<CR>", "Open java-demo"},
    ["<leader>oej"] = { ":edit " .. "~/Documents/materials/demo/demo.js<CR>", "Open js-demo"},
    ["<leader>oes"] = { ":edit " .. "~/Documents/materials/demo/demo.sh<CR>", "Open shell-demo"},
    ["<leader>oeS"] = { ":edit " .. "~/Documents/materials/demo/demo.swift<CR>", "Open swift-demo"},
    ["<leader>oep"] = { ":edit " .. "~/Documents/materials/demo/demo.pl<CR>", "Open perl-demo"},
    ["<leader>oeo"] = { ":edit " .. "~/Documents/materials/demo/demo.org<CR>", "Open org-demo"},
    ["<leader>oem"] = { ":edit " .. "~/Documents/materials/demo/demo.md<CR>", "Open markdown-demo"},
    ["<leader>oeC"] = { ":edit " .. "~/Documents/materials/demo/clojure/demo/src/demo/demo.clj<CR>", "Open coffee-demo"},
    ["<leader>oey"] = { ":edit " .. "~/Documents/materials/demo/demo.yaml<CR>", "Open yaml-demo"},
    ["<leader>oeH"] = { ":edit " .. "~/Documents/materials/demo/demo.html<CR>", "Open html-demo"},
    ["<leader>oec"] = { ":edit " .. "~/Documents/materials/demo/demo.c<CR>", "Open c-demo"},
    ["<leader>oeg"] = { ":edit " .. "~/cascode/go/src/demo/demo.go<CR>", "Open go-demo"},
    ["<leader>oeq"] = { ":edit " .. "~/Documents/materials/demo/demo.sql<CR>", "Open sql-demo"},
    ["<leader>oeE"] = { ":edit " .. "~/Documents/materials/demo/demo.exs<CR>", "Open elixir-demo"},
    ["<leader>oee"] = { ":edit " .. "~/Documents/materials/demo/demo.es<CR>", "Open es-demo"},
    ["<leader>oek"] = { ":edit " .. "~/Documents/materials/demo/demo.hs<CR>", "Open haskell-demo"},
    ["<leader>oex"] = { ":edit " .. "~/Documents/materials/mind-wave-chats/default.chat<CR>", "Open chat-demo"},
    ["<leader>oet"] = { ":edit " .. "~/Documents/materials/demo/demo.txt<CR>", "Open txt-demo"},

    ["oob"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/bookmarks.org<CR>", "Open bookmarks-org"},
    ["ood"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/tech_diary.org<CR>", "Open tech-diary-org"},
    ["ooh"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/homebrews.org<CR>", "Open homebrews-org"},
    ["oop"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/projects.org<CR>", "Open projects-org"},
    ["ool"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/learnings.org<CR>", "Open learnings-org"},
    ["oof"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/life.org<CR>", "Open life-org"},
    ["ooc"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/capture.org<CR>", "Open capture-org"},
    ["ooC"] = {":edit " .. "~/Documents/materials/cheatsheets<CR>", "Open cheatsheet-org"},
    ["oot"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/team-tasks.org<CR>", "Open team-tasks-org"},
    ["ook"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/kbd-macros.org<CR>", "Open kbd-macros-org"},
    ["ooj"] = {":edit " .. "~/Documents/materials/jira/recent-issues.org<CR>", "Open jira-org"},
    ["oor"] = {":edit " .. "~/Library/Mobile Documents/iCloud~com~appsonthemove~beorg/Documents/org/rails-guides-org/rails-guides-index.org<CR>", "Open rails-guides-org"},

  }

}

return M
