;; -*- lexical-binding: t; -*-

(add-to-list 'load-path (file-name-directory load-file-name))

(autoload 'spacemacs/helm-find-files-recursively "helm-find-files-recursively")
(autoload 'lx/open-file-in-lnav "open-file-in-lnav")
(autoload 'mfd-dired "mfd-dired")
(autoload 'mfd-name-dired "mfd-dired")
(autoload 'mfd-grep-dired "mfd-dired")
(autoload 'fd-dired "fd-dired")
(autoload 'fd-name-dired "fd-dired")
(autoload 'lx/helm-projectile-open-projects "helm-open-projects")
(autoload 'lx/helm-projectile-other-open-projects "helm-open-projects")
(autoload 'helm-cwd-buffers "helm-cwd-buffers")
(autoload 'helm-remote-buffers "helm-remote-buffers")
(autoload 'helm-ghostel-buffers "run-in-ghostel")
(autoload 'helm-pry-ghostel-arql "ghostel-arql")
(autoload 'lx/run-in-pry-ghostel "pry-ghostel")
(autoload 'lx/run-in-zsh-ghostel "zsh-ghostel")
(autoload 'helm-zsh-ghostel-ssh "zsh-ghostel-ssh")
(autoload 'helm-zsh-ghostel-ssh-run "zsh-ghostel-ssh")
(autoload 'zsh-ghostel "zsh-ghostel")
(autoload 'all-buffer-completion "all-buffer-completion")
(autoload 'current-buffer-completion "current-buffer-completion")
(autoload 'helm-ghostel-vrl "ghostel-vrl")
(autoload 'helm-ghostel-vrl-run-auto-function "ghostel-vrl")
(autoload 'helm-ghostel-prize "ghostel-prize")
(autoload 'helm-ghostel-jenkins "ghostel-jenkins")
(autoload 'ghostel-mitmproxy-transparent-proxy "ghostel-mitmproxy")
(autoload 'ghostel-mitmproxy-normal-proxy "ghostel-mitmproxy")
(autoload 'ghostel-mitmproxy-local-proxy "ghostel-mitmproxy")
(autoload 'helm-ghostel-maven-deploy "ghostel-maven")
(autoload 'helm-ghostel-maven-deploy-current-artifact "ghostel-maven")
(autoload 'helm-ghostel-maven-deploy-parent-artifact "ghostel-maven")
(autoload 'helm-ghostel-maven-deps-tree "ghostel-maven")
(autoload 'helm-ghostel-maven-deps-resolve "ghostel-maven")
(autoload 'ghostel-maven-update-local-artifact "ghostel-maven")
(autoload 'ghostel-maven-kill-local-artifact "ghostel-maven")
(autoload 'lx/run-in-ghostel "run-in-ghostel")
(autoload 'lx/run-in-projectile-ghostel "run-in-ghostel")
(autoload 'lx/run-ssh-in-zsh-ghostel "zsh-ghostel-ssh")
(autoload 'lx/run-in-ghostel/set-green-box-cursor "run-in-ghostel")
(autoload 'lx/run-in-ghostel/set-blue-bar-cursor "run-in-ghostel")
(autoload 'lx/run-in-ghostel/set-default-directory "run-in-ghostel")
(autoload 'lx/run-in-ghostel/find-remote-file "run-in-ghostel")
(autoload 'lx/run-in-ghostel/sudo-find-remote-file "run-in-ghostel")
(autoload 'lx/run-in-ghostel/save-history-to-ghostel "run-in-ghostel")
(autoload 'lx/run-in-ghostel/update-history-outcome-to-ghostel "run-in-ghostel")
(autoload 'lx/run-in-ghostel/download "run-in-ghostel")
(autoload 'lx/run-in-ghostel/upload "run-in-ghostel")
(autoload 'lx/kubectl/execute "kubectl")
(autoload 'lx/kubectl/apply-region-or-buffer "kubectl")
(autoload 'lx/kubectl/delete-region-or-buffer "kubectl")
(autoload 'lx/kubectl/istio-inject-apply-region-or-buffer "kubectl")
(autoload 'lx/kubectl/istio-inject-delete-region-or-buffer "kubectl")
(autoload 'tail-f "tail-f")
(autoload 'visidata-mode "visidata")
(autoload 'arthas-class-reload-docker "arthas-class-reloader")
(autoload 'arthas-class-reload-k8s "arthas-class-reloader")
(autoload 'ghostel-rails/run "ghostel-rails")
(autoload 'ghostel-rails/rails-server "ghostel-rails")
(autoload 'ghostel-rails/rails-dev "ghostel-rails")
(autoload 'ghostel-rails/sidekiq "ghostel-rails")
(autoload 'ghostel-agent-run-claude "ghostel-agent")
(autoload 'ghostel-agent-run-aliyun-token-plan-claude "ghostel-agent")
(autoload 'ghostel-agent-run-deepseek-claude "ghostel-agent")
(autoload 'ghostel-agent-run-grok "ghostel-agent")
(autoload 'ghostel-agent-run-opencode "ghostel-agent")
(autoload 'ghostel-agent-run-cursor "ghostel-agent")
(autoload 'ghostel-agent-run-agy "ghostel-agent")
(autoload 'ghostel-agent-run-omp "ghostel-agent")
(autoload 'ghostel-agent-send "ghostel-agent")

(autoload 'evil-ghostel-setup "evil-ghostel")
(autoload 'proced-enhanced-mode "proced-enhanced")
(autoload 'org-journal-grid "org-journal-grid" nil t)
(autoload 'markdown-modern-mode "markdown-modern" nil t)
(autoload 'global-markdown-modern-mode "markdown-modern" nil t)

(load-file (format "%s/%s" (file-name-directory load-file-name) "spacemacs-override.el"))
