(add-to-list 'load-path (file-name-directory load-file-name))

(autoload 'spacemacs/helm-find-files-recursively "helm-find-files-recursively")
(autoload 'lx/open-file-in-lnav "open-file-in-lnav")
(autoload 'mfd-dired "mfd-dired")
(autoload 'mfd-name-dired "mfd-dired")
(autoload 'mfd-grep-dired "mfd-dired")
(autoload 'fd-dired "fd-dired")
(autoload 'fd-name-dired "fd-dired")
(autoload 'lx/helm-projectile-open-projects "helm-open-projects")
(autoload 'lx/helm-projectile-other-open-projects "helm-open-projects")
(autoload 'helm-cwd-buffers "helm-cwd-buffers")
(autoload 'helm-vterm-buffers "run-in-vterm")
(autoload 'helm-pry-vterm-arql "vterm-arql")
(autoload 'lx/run-in-pry-vterm "pry-vterm")
(autoload 'lx/run-in-zsh-vterm "zsh-vterm")
(autoload 'helm-zsh-vterm-ssh "zsh-vterm-ssh")
(autoload 'zsh-vterm "zsh-vterm")
(autoload 'all-buffer-completion "all-buffer-completion")
(autoload 'helm-vterm-vrl "vterm-vrl")
(autoload 'helm-vterm-prize "vterm-prize")
(autoload 'helm-vterm-jenkins "vterm-jenkins")
(autoload 'vterm-mitmproxy-transparent-proxy "vterm-mitmproxy")
(autoload 'vterm-mitmproxy-normal-proxy "vterm-mitmproxy")
(autoload 'helm-vterm-maven-deploy "vterm-maven")
(autoload 'helm-vterm-maven-deploy-current-artifact "vterm-maven")
(autoload 'helm-vterm-maven-deploy-parent-artifact "vterm-maven")
(autoload 'helm-vterm-maven-deps-tree "vterm-maven")
(autoload 'helm-vterm-maven-deps-resolve "vterm-maven")
(autoload 'vterm-maven-update-local-artifact "vterm-maven")
(autoload 'vterm-maven-kill-local-artifact "vterm-maven")
(autoload 'lx/run-in-vterm "run-in-vterm")
(autoload 'lx/run-ssh-in-zsh-vterm "zsh-vterm-ssh")
(autoload 'lx/run-in-vterm/set-green-box-cursor "run-in-vterm")
(autoload 'lx/run-in-vterm/set-blue-bar-cursor "run-in-vterm")
(autoload 'lx/run-in-vterm/set-default-directory "run-in-vterm")
(autoload 'lx/kubectl/execute "kubectl")
(autoload 'lx/kubectl/apply-region-or-buffer "kubectl")
(autoload 'lx/kubectl/delete-region-or-buffer "kubectl")
(autoload 'lx/kubectl/istio-inject-apply-region-or-buffer "kubectl")
(autoload 'lx/kubectl/istio-inject-delete-region-or-buffer "kubectl")
(autoload 'tail-f "tail-f")
(autoload 'visidata-mode "visidata")

(load-file (format "%s/%s" (file-name-directory load-file-name) "spacemacs-override.el"))
