resolutions:
  - name: A
    width: 1920
  - name: B
    width: 1280
  - name: ALL
    width: 0

apps:
  - name: iTerm
    actions:
      ALL: "set:0,0,1,1"
  - name: ScreenFlow
    actions:
      ALL: "set:0,0,1,1"
  - name: Safari
    actions:
      ALL: "set:0,0,1,1"
  - name: MacDown
    actions:
      ALL: "set:0,0,1,1"
  - name: Xcode
    actions:
      ALL: "set:0,0,1,1"
  - name: "Google Chrome"
    actions:
      ALL: "set:0,0,1,1"
  - name: "Sublime Text"
    actions:
      ALL: "set:0,0,1,1"
  - name: Dash
    actions:
      A: "set:0.1,0.1,0.9,0.9"
      B: "set:0,0,1,1"
  - name: QQ
    actions:
      ALL: "move:0.5,0.5"
  - name: Telegram
    actions:
      ALL: "move:0.5,0.5"
  - name: AliWangwang
    actions:
      ALL: "move:0.5,0.5"
  - name: Eudic
    actions:
      ALL: "move:0.5,0.5"
  - name: NeteaseMusic
    actions:
      ALL: "move:0.5,0.5"

