#The ports to redirect to proxy
redir_ports = "{http, https}"

#The address the transparent proxy is listening on
tproxy = "127.0.0.1 port 8888"

rdr on en0 inet proto tcp from any to any port $redir_ports -> $tproxy
