#!/bin/bash

dest_dir=${1:-$HOME}
script_dir=$(cd $(dirname $0); pwd)

config_file_links=(
  '.ackrc -> .ackrc'
  '.agenda_files -> emacs-config/.agenda_files'
  '.agignore -> .agignore'
  '.authinfo -> secrets/.authinfo'
  '.autolayouts.yaml -> .autolayouts.yaml'
  '.babelrc -> .babelrc'
  '.bash_profile -> .bash_profile'
  '.bashrc -> .bashrc'
  '.dns_switcher_options.yaml -> .dns_switcher_options.yaml'
  '.emacs-profiles.el -> chemacs2/.emacs-profiles.el'
  '.gemrc -> .gemrc'
  '.gitconfig -> secrets/.gitconfig'
  '.gitignore -> .gitignore'
  '.gitignore_global -> .gitignore_global'
  '.globalrc -> .gnu_globalrc'
  '.gvimrc -> .gvimrc'
  '.htoprc -> .htoprc'
  '.hyper.js -> .hyper.js'
  '.icrt.conf -> .icrt.conf'
  '.ideavim_actions.txt -> .ideavim_actions.txt'
  '.ideavimrc -> .ideavimrc'
  '.imapnotifyrc.json -> secrets/.imapnotifyrc.json'
  '.irbrc -> .irbrc'
  '.jenkins-builder.yaml -> secrets/.jenkins-builder.yaml'
  '.linkdispatch -> .linkdispatch'
  '.mitmproxy.pf.conf -> .mitmproxy.pf.conf'
  '.offlineimaprc -> secrets/.offlineimaprc'
  '.pf.conf -> secrets/.pf.conf'
  '.prizerc -> .prizerc'
  '.profile -> .profile'
  '.proton -> .proton'
  '.proxyswitcher.rc -> .proxyswitcher.rc'
  '.pry-csv-excel-helper.rb -> pry-csv-excel-helper.rb'
  '.pryrc -> .pryrc'
  '.rabbitmqadmin.conf -> secrets/.rabbitmqadmin.conf'
  '.rails.gitignore -> .rails.gitignore'
  '.rails.template -> .rails.template'
  '.railsrc -> .railsrc'
  '.rexerc -> .rexerc'
  '.rotrc -> .rotrc'
  '.rspec-git -> .rspec-git'
  '.screenrc -> .screenrc'
  '.secretenv -> secrets/.secretenv'
  '.spring.rb -> .spring.rb'
  '.ss-tunnel-config.json -> secrets/.ss-tunnel-config.json'
  '.sublimious -> .sublimious'
  '.vimrc_back -> .vimrc'
  '.visidatarc -> .visidatarc'
  '.vrl.yml -> secrets/.vrl.yml'
  '.windowmaxrc -> .windowmaxrc'
  '.xonshrc -> xonshrc'
  '.zlogin -> .zlogin'
  '.zprofile -> .zprofile'
  '.zshenv -> .zshenv'
  '.zshrc -> .zshrc'
)

for link in "${config_file_links[@]}"; do
    echo ln -nfs "$script_dir/${link##* }" "$dest_dir/${link%% *}"
done

