[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"


[[mgr.prepend_keymap]]
on   = [ "o" ]
run  = "plugin cursor-open"
desc = "Open the file with cursor"

[[mgr.prepend_keymap]]
on   = [ "A" ]
run  = "hidden toggle"
desc = "Toggle hidden files"

[[mgr.prepend_keymap]]
on   = [ "<A-Enter>" ]
run  = "plugin cursor-open"
desc = "Open the file with cursor"

[[mgr.prepend_keymap]]
on   = [ "M" ]
run  = [ "toggle", "arrow 1"]
desc = "Toggle the selection state of the current file"

[[mgr.prepend_keymap]]
on   = [ "Z" ]
run  = "plugin fzf-autojump"
desc = "Jump to a directory with fzf"

[[mgr.prepend_keymap]]
on   = [ "z", "j" ]
run  = "plugin fzf-autojump"
desc = "Jump to a directory with fzf"

[[mgr.prepend_keymap]]
on   = [ "<Space>", "j" ]
run  = "plugin fzf-autojump"
desc = "Jump to a directory with fzf"


[[mgr.prepend_keymap]]
on   = [ "T" ]
run  = "plugin fzf"
desc = "Jump to a directory with fzf"


[[mgr.prepend_keymap]]
on   = [ "u" ]
run = "leave"
desc = "Enter parent directory"


[[mgr.prepend_keymap]]
on   = [ "U" ]
run  = "toggle_all --state=off"
desc = "unselect all files"

[[mgr.prepend_keymap]]
on   = [ "<C-a>" ]
run  = "toggle_all --state=on"
desc = "toggle select all files"

[[mgr.prepend_keymap]]
on   = [ "-" ]
run = "leave"
desc = "Enter parent directory"


[[mgr.prepend_keymap]]
on = "0"
run = "plugin toggle-layout"
desc = "Toggle between current-only and full layout"

[[mgr.prepend_keymap]]
on   = [ "<A-->" ]
run  = "plugin dir-hist toggle"
desc = "Toggle between current and previous directory"

[[mgr.prepend_keymap]]
on   = [ "<A-p>" ]
run  = "plugin dir-hist previous"
desc = "Switch to previous directory in history"

[[mgr.prepend_keymap]]
on  = [ "l" ]
run = "link"
desc = "Symlink the absolute path of yanked files"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
[[mgr.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg"
desc = "find file by content (fuzzy match)"
[[mgr.prepend_keymap]]
on   = [ "f","G" ]
run  = "plugin fg -- rg"
desc = "find file by content (ripgrep match)"
[[mgr.prepend_keymap]]
on   = [ "f","n" ]
run  = "plugin fg -- fzf"
desc = "find file by filename"
[[mgr.prepend_keymap]]
on   = [ "f","f" ]
run  = "filter --smart"
desc = "filter"
[[mgr.prepend_keymap]]
on   = [ "<A-c>" ]
run  = "plugin fg -- fzf_cwd"
desc = "find file in cwd"
[[mgr.prepend_keymap]]
on   = [ "<C-t>" ]
run  = "plugin fg -- fzf_all"
desc = "find file or dir by filename"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "a"]
run = "cd -- ~/global-claude/"
desc = "Jump to ~/global-claude/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "A"]
run = "cd -- /Applications/"
desc = "Jump to /Applications/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "b"]
run = "cd -- ~/blog/"
desc = "Jump to ~/blog/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "B"]
run = "cd -- ~/bin/"
desc = "Jump to ~/bin/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "C"]
run = "cd -- ~/Cafe/"
desc = "Jump to ~/Cafe/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "c"]
run = "cd -- ~/.config/"
desc = "Jump to ~/.config/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "<C-c>"]
run = "cd -- ~/cascode/"
desc = "Jump to ~/cascode/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "d"]
run = "cd -- ~/Downloads/"
desc = "Jump to ~/Downloads/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "D"]
run = "cd -- ~/Documents/"
desc = "Jump to ~/Documents/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "f"]
run = "cd -- ~/.fzf/"
desc = "Jump to ~/.fzf/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "g"]
run = "cd -- ~/cascode/github.com/"
desc = "Jump to ~/cascode/github.com/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "H"]
run = "cd -- /home"
desc = "Jump to /home'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "h"]
run = "cd -- ~/"
desc = "Jump to ~/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "i"]
run = "cd -- ~/Library/Mobile\\ Documents/com~apple~CloudDocs/"
desc = "Jump to ~/Library/Mobile Documents/com~apple~CloudDocs/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "k"]
run = "cd -- ~/sd/"
desc = "Jump to ~/sd/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "K"]
run = "cd -- ~/kt/"
desc = "Jump to ~/kt/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "l"]
run = "cd -- ~/lab"
desc = "Jump to ~/lab'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "p"]
run = "cd -- ~/Library/Application Support/"
desc = "Jump to ~/Library/Application Support/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "L"]
run = "cd -- ~/Library/Application Support/"
desc = "Jump to ~/Library/Application Support/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "P"]
run = "cd -- ~/Library/Preferences/"
desc = "Jump to ~/Library/Preferences/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "M"]
run = "cd -- ~/Movies/"
desc = "Jump to ~/Movies/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "m"]
run = "cd -- ~/Documents/materials/"
desc = "Jump to ~/Documents/materials/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "s"]
run = "cd -- ~/Documents/materials/scratches/"
desc = "Jump to ~/Documents/materials/scratches/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "S"]
run = "cd -- ~/snips/"
desc = "Jump to ~/snips/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "<C-s>"]
run = "cd -- ~/Documents/materials/snippets"
desc = "Jump to ~/Documents/materials/snippets'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "e"]
run = "cd -- ~/.emacs.spacemacs.d"
desc = "Jump to ~/.emacs.spacemacs.d'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "z"]
run = "cd -- ~/.spacezsh/"
desc = "Jump to ~/.spacezsh/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "Z"]
run = "cd -- ~/.oh-my-zsh/"
desc = "Jump to ~/.oh-my-zsh/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "/"]
run = "cd -- /"
desc = "Jump to /'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "o"]
run = "cd -- ~/Library/Mobile\\ Documents/iCloud~com~appsonthemove~beorg/Documents/org"
desc = "Jump to ~/Library/Mobile\\ Documents/iCloud~com~appsonthemove~beorg/Documents/org'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "j"]
run = "cd -- ~/Documents/materials/journal"
desc = "Jump to ~/Documents/materials/journal'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "J"]
run = "cd -- ~/Documents/materials/jira"
desc = "Jump to ~/Documents/materials/jira'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "n"]
run = "cd -- ~/Documents/materials/notes"
desc = "Jump to ~/Documents/materials/notes'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "N"]
run = "cd -- ~/Documents/evernotes"
desc = "Jump to ~/Documents/evernotes'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "w"]
run = "cd -- ~/Documents/materials/webclips"
desc = "Jump to ~/Documents/materials/webclips'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "v"]
run = "cd -- /Volumes"
desc = "Jump to /Volumes'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "T"]
run = "cd -- ~/.tmux"
desc = "Jump to ~/.tmux'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "t"]
run = "cd -- ~/tmp/"
desc = "Jump to ~/tmp/'"

[[pick.prepend_keymap]]
on = ["q"]
run = [ "close" ]
desc = "Close the picker"

[[mgr.prepend_keymap]]
on = ["<C-o>", "c"]
run = "shell 'cursor .'"
desc = "Open current directory in Cursor"


[[mgr.prepend_keymap]]
on = ["<C-o>", "t"]
run = "shell 'trae .'"
desc = "Open current directory in Trae"

[[mgr.prepend_keymap]]
on = ["<C-o>", "v"]
run = "shell 'code .'"
desc = "Open current directory in VSCode"

[[mgr.prepend_keymap]]
on = ["<C-o>", "e"]
run = "shell 'ee .'"
desc = "Open current directory in Emacs"

[[mgr.prepend_keymap]]
on = [ "<A-g>"]
run = "plugin magit"
desc = "Open magit"
