[[manager.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin --sync smart-enter"
desc = "Enter the child directory, or open the file"

[[manager.prepend_keymap]]
on   = [ "z" ]
run  = "plugin fzf-autojump"
desc = "Jump to a directory with fzf"

[[manager.prepend_keymap]]
on   = [ "T" ]
run  = "plugin fzf"
desc = "Jump to a directory with fzf"


[[manager.prepend_keymap]]
on   = [ "u" ]
run = "leave"
desc = "Enter parent directory"

[[manager.prepend_keymap]]
on   = [ "-" ]
run = "leave"
desc = "Enter parent directory"
