[[mgr.prepend_keymap]]
on   = [ "<Enter>" ]
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"


[[mgr.prepend_keymap]]
on   = [ "o" ]
run  = "plugin cursor-open"
desc = "Open the file with cursor"


[[mgr.prepend_keymap]]
on   = [ "<A-Enter>" ]
run  = "plugin cursor-open"
desc = "Open the file with cursor"

[[mgr.prepend_keymap]]
on   = [ "M" ]
run  = [ "toggle", "arrow 1"]
desc = "Toggle the selection state of the current file"

[[mgr.prepend_keymap]]
on   = [ "Z" ]
run  = "plugin fzf-autojump"
desc = "Jump to a directory with fzf"

[[mgr.prepend_keymap]]
on   = [ "z", "j" ]
run  = "plugin fzf-autojump"
desc = "Jump to a directory with fzf"

[[mgr.prepend_keymap]]
on   = [ "<Space>", "j" ]
run  = "plugin fzf-autojump"
desc = "Jump to a directory with fzf"


[[mgr.prepend_keymap]]
on   = [ "T" ]
run  = "plugin fzf"
desc = "Jump to a directory with fzf"


[[mgr.prepend_keymap]]
on   = [ "u" ]
run = "leave"
desc = "Enter parent directory"

[[mgr.prepend_keymap]]
on   = [ "U" ]
run  = "toggle_all --state=off"
desc = "unselect all files"

[[mgr.prepend_keymap]]
on   = [ "<C-a>" ]
run  = "toggle_all --state=on"
desc = "toggle select all files"

[[mgr.prepend_keymap]]
on   = [ "-" ]
run = "leave"
desc = "Enter parent directory"

[[mgr.prepend_keymap]]
on  = [ "l" ]
run = "link"
desc = "Symlink the absolute path of yanked files"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"
[[mgr.prepend_keymap]]
on   = [ "f","g" ]
run  = "plugin fg"
desc = "find file by content (fuzzy match)"
[[mgr.prepend_keymap]]
on   = [ "f","G" ]
run  = "plugin fg -- rg"
desc = "find file by content (ripgrep match)"
[[mgr.prepend_keymap]]
on   = [ "f","n" ]
run  = "plugin fg -- fzf"
desc = "find file by filename"
[[mgr.prepend_keymap]]
on   = [ "f","f" ]
run  = "filter --smart"
desc = "filter"
[[mgr.prepend_keymap]]
on   = [ "<A-c>" ]
run  = "plugin fg -- fzf_cwd"
desc = "find file in cwd"
[[mgr.prepend_keymap]]
on   = [ "<C-t>" ]
run  = "plugin fg -- fzf_all"
desc = "find file or dir by filename"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "A"]
run = "plugin dirs -- /Applications/"
desc = "Jump to /Applications/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "b"]
run = "plugin dirs -- ~/blog/"
desc = "Jump to ~/blog/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "B"]
run = "plugin dirs -- ~/bin/"
desc = "Jump to ~/bin/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "C"]
run = "plugin dirs -- ~/Cafe/"
desc = "Jump to ~/Cafe/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "c"]
run = "plugin dirs -- ~/.config/"
desc = "Jump to ~/.config/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "<C-c>"]
run = "plugin dirs -- ~/cascode/"
desc = "Jump to ~/cascode/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "d"]
run = "plugin dirs -- ~/Downloads/"
desc = "Jump to ~/Downloads/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "D"]
run = "plugin dirs -- ~/Documents/"
desc = "Jump to ~/Documents/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "f"]
run = "plugin dirs -- ~/.fzf/"
desc = "Jump to ~/.fzf/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "g"]
run = "plugin dirs -- ~/cascode/github.com/"
desc = "Jump to ~/cascode/github.com/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "H"]
run = "plugin dirs -- /home"
desc = "Jump to /home'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "h"]
run = "plugin dirs -- ~/"
desc = "Jump to ~/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "i"]
run = "plugin dirs -- ~/Library/Mobile\\ Documents/com~apple~CloudDocs/"
desc = "Jump to ~/Library/Mobile Documents/com~apple~CloudDocs/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "k"]
run = "plugin dirs -- ~/sd/"
desc = "Jump to ~/sd/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "K"]
run = "plugin dirs -- ~/kt/"
desc = "Jump to ~/kt/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "l"]
run = "plugin dirs -- ~/Library/Application\\ Support/"
desc = "Jump to ~/Library/Application\\ Support/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "L"]
run = "plugin dirs -- ~/Library/Preferences/"
desc = "Jump to ~/Library/Preferences/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "M"]
run = "plugin dirs -- ~/Movies/"
desc = "Jump to ~/Movies/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "m"]
run = "plugin dirs -- ~/Documents/materials/"
desc = "Jump to ~/Documents/materials/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "s"]
run = "plugin dirs -- ~/Documents/materials/scratches/"
desc = "Jump to ~/Documents/materials/scratches/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "S"]
run = "plugin dirs -- ~/snips/"
desc = "Jump to ~/snips/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "<C-s>"]
run = "plugin dirs -- ~/Documents/materials/snippets"
desc = "Jump to ~/Documents/materials/snippets'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "e"]
run = "plugin dirs -- ~/.emacs.spacemacs.d"
desc = "Jump to ~/.emacs.spacemacs.d'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "z"]
run = "plugin dirs -- ~/.spacezsh/"
desc = "Jump to ~/.spacezsh/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "Z"]
run = "plugin dirs -- ~/.oh-my-zsh/"
desc = "Jump to ~/.oh-my-zsh/'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "/"]
run = "plugin dirs -- /"
desc = "Jump to /'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "o"]
run = "plugin dirs -- ~/Library/Mobile\\ Documents/iCloud~com~appsonthemove~beorg/Documents/org"
desc = "Jump to ~/Library/Mobile\\ Documents/iCloud~com~appsonthemove~beorg/Documents/org'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "j"]
run = "plugin dirs -- ~/Documents/materials/journal"
desc = "Jump to ~/Documents/materials/journal'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "J"]
run = "plugin dirs -- ~/Documents/materials/jira"
desc = "Jump to ~/Documents/materials/jira'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "n"]
run = "plugin dirs -- ~/Documents/materials/notes"
desc = "Jump to ~/Documents/materials/notes'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "N"]
run = "plugin dirs -- ~/Documents/evernotes"
desc = "Jump to ~/Documents/evernotes'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "w"]
run = "plugin dirs -- ~/Documents/materials/webclips"
desc = "Jump to ~/Documents/materials/webclips'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "v"]
run = "plugin dirs -- /Volumes"
desc = "Jump to /Volumes'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "T"]
run = "plugin dirs -- ~/.tmux"
desc = "Jump to ~/.tmux'"
[[mgr.prepend_keymap]]
on = ["<Space>", "o", "d", "t"]
run = "plugin dirs -- ~/tmp/"
desc = "Jump to ~/tmp/'"

[[pick.prepend_keymap]]
on = ["q"]
run = [ "close" ]
desc = "Close the picker"
