[mgr]
linemode = 'full'
sort_dir_first = false
sort_by = 'mtime'
sort_reverse = true
show_hidden = true

[opener]
edit = [
	{ run = 'open-file-for-yazi %s', block = true, desc = "Smart Open" },
	{ run = 'nvim %s', block = true, desc = "Edit with nvim" },
	{ run = 'ee %s', block = false, desc = "Edit with Emacs" },
	{ run = 'open-with-neovide.sh %s', block = false, desc = "Edit with Neovide" },
	{ run = '/Applications/Cursor.app/Contents/MacOS/Cursor %s', block = false, desc = "Edit with Cursor" },
  { run = 'code %s', block = false, desc = "Edit with VS Code" },
  { run = 'trae %s', block = false, desc = "Edit with Trae" },
]
play = [
	{ run = 'open %s' },
]
open = [
	{ run = 'open %s', desc = "Open" },
]

[plugin]
prepend_previewers = [
  { url = "*.ovpn", run = "code" },
  { url = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { url = "*.markdown", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' },
  { url = "*.docx", run = 'piper -- markitdown "$1" | CLICOLOR_FORCE=1 glow -w=$w -s=dark' },
  { url = "*.doc", run = 'piper -- markitdown "$1" | CLICOLOR_FORCE=1 glow -w=$w -s=dark' },
  { url = "*.csv", run = 'duckdb' },
  { url = "*.xlsx", run = 'duckdb' }
]

prepend_preloaders = [  
  { url = "*.csv", run = "duckdb", multi = false },  
  { url = "*.tsv", run = "duckdb", multi = false },  
  { url = "*.xlsx", run = "duckdb", multi = false }
]

[preview]
max_width = 1600
max_height = 2560