;; (defun lx/clojure-repl ()
;;   (interactive)
;;   (require 'cider)
;;   (with-current-buffer (find-file-noselect "~/Documents/materials/demo/clojure/demo")
;;     (let ((default-directory  "~/Documents/materials/demo/clojure/demo"))
;;       (unless (ignore-error user-error (cider-current-repl 'clj 'ensure))
;;         (call-interactively 'cider-jack-in-clj))
;;       (call-interactively 'cider-switch-to-repl-buffer))))


(defun lx/clojure-repl ()
  (interactive)
  (require 'cider)
  (with-current-buffer (find-file-noselect "~/Documents/materials/demo/clojure/demo")
    (let ((default-directory  "~/Documents/materials/demo/clojure/demo"))
      (unless (--filter (string-match-p "^\\*nrepl-server clojure/demo" (buffer-name it)) (buffer-list))
        (message "Starting CIDER server...")
        (call-interactively 'cider-jack-in-clj))
      (call-interactively 'cider-switch-to-repl-buffer))))
