(defun lx/reset-lsp-company-backends ()
  (interactive)
  (let ((preferred '(company-files company-capf company-tabnine :with company-yasnippet))
        backends)
    (dolist (backend company-backends backends)
      (if (consp backend)
          (push (append (seq-filter (lambda (it) (not (seq-contains-p preferred it))) backend) '(:with company-yasnippet)) backends)
        (if (not (seq-contains-p preferred backend))
            (push (list backend :with 'company-yasnippet) backends))))
    (setq-local company-backends (cons preferred backends))))
