(defun lx/keyboard-quit ()
  (interactive)
  (spacemacs/evil-search-clear-highlight) (copilot-clear-overlay) (keyboard-quit))

(defun lx/tab (arg)
  (interactive "P")
  (or (copilot-accept-completion) (indent-for-tab-command arg)))

(defun lx/reset-hybrid-state-cursor-type-after-tab ()
   (interactive)
   (when (and (eq 'lx/tab this-command) (eq 'hybrid evil-state))
     (setq cursor-type '(bar . 2))
     (set-cursor-color "SkyBlue2")))

(defun lx/copilot-accept-or-forward-word (arg)
  (interactive "P")
  (if (bound-and-true-p copilot--overlay)
      (copilot-accept-completion-by-word 1)
    (call-interactively 'forward-word)))

(defun lx/copilot-accept-or-next-line (arg)
  (interactive "P")
  (if (bound-and-true-p copilot--overlay)
      (copilot-accept-completion-by-line 1)
    (call-interactively 'next-line)))
