;;; init.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-

(add-to-list 'load-path (file-name-directory load-file-name))

;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:


;;;### (autoloads nil "autojump" "autojump.el" (0 0 0 0))
;;; Generated autoloads from autojump.el

(autoload 'lx/autojump-add "autojump")

;;;***

;;;### (autoloads nil "base64" "base64.el" (0 0 0 0))
;;; Generated autoloads from base64.el

(autoload 'base64-decode-utf8-region "base64" "\


\(fn START END)" t)

(autoload 'base64-encode-utf8-region "base64" "\


\(fn START END)" t)

;;;***

;;;### (autoloads nil "browse-in-alfred" "browse-in-alfred.el" (0
;;;;;;  0 0 0))
;;; Generated autoloads from browse-in-alfred.el

(autoload 'lx/browse-in-alfred "browse-in-alfred" "\


\(fn PATH)")

(autoload 'lx/browse-file-or-directory-in-alfred "browse-in-alfred" "\
Open current file in external application.
If the universal prefix argument is used then open the folder
containing the current file by the default explorer.

\(fn ARG)" t)

;;;***

;;;### (autoloads nil "browse-url-in-safari" "browse-url-in-safari.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from browse-url-in-safari.el

(autoload 'lx/browse-url-in-safari "browse-url-in-safari" "\


\(fn URL)" t)

;;;***

;;;### (autoloads nil "buffers" "buffers.el" (0 0 0 0))
;;; Generated autoloads from buffers.el

(autoload 'lx/kill-buffers "buffers" "\


\(fn BUFFERS)" t)

(autoload 'lx/get-all-buffers-except "buffers" "\


\(fn KEEP-BUFFER-NAMES)" t)

(autoload 'lx/kill-except-spacemacs-and-scratch-buffers "buffers" nil t)

(autoload 'lx/kill-all-except-default "buffers" nil t)

(autoload 'lx/switch-to-warning-buffer "buffers" "\


\(fn ARG)" t)

(autoload 'lx/delete-window-or-bury-buffer "buffers" nil t)

(autoload 'lx/new-untitled-buffer "buffers" nil t)

(autoload 'lx/new-untitled-buffer-same-window "buffers" nil t)

(autoload 'lx/kill-buffer-and-delete-window "buffers" nil t)

(autoload 'lx/kill-buffer-interactively "buffers" nil t)

(autoload 'lx/switch-to-dired-buffer "buffers" nil t)

;;;***

;;;### (autoloads nil "byte-compile-current-buffer-file" "byte-compile-current-buffer-file.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from byte-compile-current-buffer-file.el

(autoload 'byte-compile-current-buffer-file "byte-compile-current-buffer-file" nil t)

;;;***

;;;### (autoloads nil "capture-note" "capture-note.el" (0 0 0 0))
;;; Generated autoloads from capture-note.el

(autoload 'lx/nbsp-to-space "capture-note" "\
Convert HTML non-breaking spaces to plain spaces in S.

\(fn S)")

(autoload 'lx/conform-filename "capture-note" "\


\(fn FILENAME)")

(autoload 'lx/refine-web-string "capture-note" "\


\(fn STR)")

(autoload 'lx/refine-filename "capture-note" "\


\(fn FILENAME)")

(autoload 'lx/capture-note "capture-note" "\


\(fn TITLE LINK BODY)")

(autoload 'lx/download-org-images "capture-note" nil t)

;;;***

;;;### (autoloads nil "clojure-repl" "clojure-repl.el" (0 0 0 0))
;;; Generated autoloads from clojure-repl.el

(autoload 'lx/clojure-repl "clojure-repl" nil t)

;;;***

;;;### (autoloads nil "company-indirect-sql-backend" "company-indirect-sql-backend.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from company-indirect-sql-backend.el

(autoload 'company-indirect-sql-backend "company-indirect-sql-backend" "\
dabbrev-like `company-mode' backend for code.
The backend looks for all symbols in the current buffer that aren't in
comments or strings.

\(fn COMMAND &optional ARG &rest IGNORED)" t)

;;;***

;;;### (autoloads nil "complete" "complete.el" (0 0 0 0))
;;; Generated autoloads from complete.el

(autoload 'lx/reset-lsp-company-backends "complete" nil t)

;;;***

;;;### (autoloads nil "copy-org-links-at-point" "copy-org-links-at-point.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from copy-org-links-at-point.el

(autoload 'get-git-link "copy-org-links-at-point" "\


\(fn REMOTE START END)" t)

(autoload 'get-local-file-link "copy-org-links-at-point")

(autoload 'copy-org-links-at-point "copy-org-links-at-point" nil t)

;;;***

;;;### (autoloads nil "core" "core.el" (0 0 0 0))
;;; Generated autoloads from core.el

(autoload 'lx/keyboard-quit "core" nil t)

(autoload 'lx/tab "core" "\


\(fn ARG)" t)

(autoload 'lx/reset-hybrid-state-cursor-type-after-tab "core" nil t)

(autoload 'lx/copilot-accept-or-forward-word "core" "\


\(fn ARG)" t)

(autoload 'lx/copilot-accept-or-next-line "core" "\


\(fn ARG)" t)

(autoload 'lx/switch-to-buffer "core" nil t)

(autoload 'lx/switch-to-project-or-all-buffer "core" nil t)

(autoload 'lx/is-remote-buffer "core")

(autoload 'lx/get-remote-buffer-host "core")

(autoload 'lx/make-frame "core" nil t)

(autoload 'lx/switch-to-project-3rd-buffer "core" nil t)

(autoload 'lx/save-buffer "core" nil t)

(autoload 'lx/open-emacs-init-file "core" nil t)

;;;***

;;;### (autoloads nil "current-dir-name" "current-dir-name.el" (0
;;;;;;  0 0 0))
;;; Generated autoloads from current-dir-name.el

(autoload 'lx/current-buffer-dir-name "current-dir-name")

(autoload 'lx/open-current-bufffer-dir-in-finder "current-dir-name" nil t)

;;;***

;;;### (autoloads nil "current-directory" "current-directory.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from current-directory.el

(autoload 'lx/current-directory "current-directory")

;;;***

;;;### (autoloads nil "date-times" "date-times.el" (0 0 0 0))
;;; Generated autoloads from date-times.el

(autoload 'lx/insert-timestamp "date-times" "\
Read a timestamp from the user and insert it at point." t)

(autoload 'lx/parse-timestamp "date-times" nil t)

;;;***

;;;### (autoloads nil "delete-window-or-bury-buffer" "delete-window-or-bury-buffer.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from delete-window-or-bury-buffer.el

(autoload 'delete-window-or-bury-buffer "delete-window-or-bury-buffer" nil t)

;;;***

;;;### (autoloads nil "ediff-copy-both-to-c" "ediff-copy-both-to-c.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from ediff-copy-both-to-c.el

(autoload 'ediff-copy-both-to-C "ediff-copy-both-to-c" nil t)

(autoload 'add-d-to-ediff-mode-map "ediff-copy-both-to-c")

;;;***

;;;### (autoloads nil "emms-ext" "emms-ext.el" (0 0 0 0))
;;; Generated autoloads from emms-ext.el

(autoload 'lx/load-emms-libs "emms-ext")

(autoload 'lx/load-or-switch-to-emms "emms-ext" nil t)

;;;***

;;;### (autoloads nil "evil-commands-ext" "evil-commands-ext.el" (0 0 0 0))
;;; Generated autoloads from evil-commands-ext.el

(autoload 'vi/del-org-props "evil-commands-ext" nil t)

(autoload 'vi/convert-org-example-to-src "evil-commands-ext" "\


\(fn LANG)" t)

(autoload 'vi/convert-org-src-to-example "evil-commands-ext" nil t)

(autoload 'vi/strip-ansi-code "evil-commands-ext" nil t)

(autoload 'vi/del-github-data-uri "evil-commands-ext" nil t)

(autoload 'lx/evil-next-10-lines "evil-commands-ext" nil t)

(autoload 'lx/evil-previous-10-lines "evil-commands-ext" nil t)

(autoload 'lx/evil-substitute-and-indent "evil-commands-ext" nil t)

(autoload 'lx/evil-smart-toggle-fold "evil-commands-ext" nil t)

(autoload 'lx/evil-smart-goto-file "evil-commands-ext" nil t)

(autoload 'lx/evil-insert-newline-below "evil-commands-ext" nil t)

;;;***

;;;### (autoloads nil "gantt" "gantt.el" (0 0 0 0))
;;; Generated autoloads from gantt.el

(autoload 'gantt "gantt" nil t)

;;;***

;;;### (autoloads nil "git-funcs" "git-funcs.el" (0 0 0 0))
;;; Generated autoloads from git-funcs.el

(autoload 'lx/magit-status-smart "git-funcs" nil t)

(autoload 'lx/magit-smart-checkout "git-funcs" nil t)

(autoload 'lx/magit-status-async-and-show "git-funcs" nil t)

(autoload 'lx/magit-file-undo-checkout "git-funcs" nil t)

(autoload 'lx/magit-pull-and-show "git-funcs" nil t)

(autoload 'lx/magit-push-and-show "git-funcs" nil t)

(autoload 'lx/magit-merge-interactive "git-funcs" nil t)

;;;***

;;;### (autoloads nil "git-link-handler" "git-link-handler.el" (0
;;;;;;  0 0 0))
;;; Generated autoloads from git-link-handler.el

(autoload 'git-link-gitlab-no-https "git-link-handler" "\


\(fn HOSTNAME DIRNAME FILENAME BRANCH COMMIT START END)")

;;;***

;;;### (autoloads nil "global-org-capture" "global-org-capture.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from global-org-capture.el

(autoload 'lx/make-global-org-capture "global-org-capture" "\


\(fn SYSTEM-PORCESS)")

(autoload 'lx/delete-global-org-capture-frame "global-org-capture")

;;;***

;;;### (autoloads nil "helm-ag-searching" "helm-ag-searching.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from helm-ag-searching.el

(autoload 'lx/helm-ag-search-prefilled-pattern "helm-ag-searching" "\


\(fn KEYWORD)")

(autoload 'lx/helm-ag-search-pry-breakpoints "helm-ag-searching" nil t)

;;;***

;;;### (autoloads nil "helm-files-ext" "helm-files-ext.el" (0 0 0 0))
;;; Generated autoloads from helm-files.el

(autoload 'lx/helm-find-project-files "helm-files-ext" nil t)

(autoload 'lx/helm-dired-histories "helm-files-ext" nil t)

(autoload 'lx/projectile-dired-histories "helm-files-ext")

(autoload 'lx/helm-projectile-dired-histories "helm-files-ext" nil t)

;;;***

;;;### (autoloads nil "helm-pinyin-match-function" "helm-pinyin-match-function.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from helm-pinyin-match-function.el

(autoload 'helm-mm-pinyin-match "helm-pinyin-match-function" "\


\(fn STR &optional (PATTERN helm-pattern))")

;;;***

;;;### (autoloads nil "idea-helpers" "idea-helpers.el" (0 0 0 0))
;;; Generated autoloads from idea-helpers.el

(autoload 'lx/switch-to-layout-of-project "idea-helpers" "\


\(fn PROJECT)")

(autoload 'lx/open-with-idea "idea-helpers" nil t)

;;;***

;;;### (autoloads nil "indent-paste" "indent-paste.el" (0 0 0 0))
;;; Generated autoloads from indent-paste.el

(autoload 'lx/indent-paste "indent-paste" nil t)

;;;***

;;;### (autoloads nil "jump-to-definition-of-symbol-at-point" "jump-to-definition-of-symbol-at-point.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from jump-to-definition-of-symbol-at-point.el

(autoload 'jump-to-definition-of-symbol-at-point "jump-to-definition-of-symbol-at-point" nil t)

(autoload 'jump-to-definition-of-symbol-at-point-other-window "jump-to-definition-of-symbol-at-point" nil t)

(autoload 'robe-jump-other-window "jump-to-definition-of-symbol-at-point" "\
Jump to the method or module at point, prompt for module or file if necessary.
If invoked with a prefix or no symbol at point, delegate to `robe-ask'.

\(fn ARG)" t)

(autoload 'robe-jump-to-module-other-window "jump-to-definition-of-symbol-at-point" "\
Prompt for module, jump to a file where it has method definitions.

\(fn NAME)" t)

(autoload 'robe-ask-other-window "jump-to-definition-of-symbol-at-point" "\
Prompt for module, method, and jump to its definition." t)

;;;***

;;;### (autoloads nil "layouts" "layouts.el" (0 0 0 0))
;;; Generated autoloads from layouts.el

(autoload 'lx/swap-list-elem "layouts" "\


\(fn LIST A B)")

(autoload 'lx/next-list-index "layouts" "\


\(fn LIST IDX)")

(autoload 'lx/previous-list-index "layouts" "\


\(fn LIST IDX)")

(autoload 'lx/current-layout-index "layouts")

(autoload 'lx/move-layout-forward "layouts" nil t)

(autoload 'lx/move-layout-backward "layouts" nil t)

(autoload 'lx/helm-persp-replace-project "layouts" "\


\(fn ARG)" t)

(autoload 'lx/persp-swith-to-buffer-project "layouts" nil t)

(autoload 'lx/kill-all-non-default-layouts "layouts" nil t)

;;;***

;;;### (autoloads nil "lx-set-monospaced-font" "lx-set-monospaced-font.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from lx-set-monospaced-font.el

(autoload 'lx/set-monospaced-font "lx-set-monospaced-font" "\


\(fn ENGLISH CHINESE ENGLISH-RETINA-SIZE CHINESE-RETINA-SIZE ENGLISH-NORMAL-SIZE CHINESE-NORMAL-SIZE)")

(autoload 'lx/set-monospaced-font/increase-font-size "lx-set-monospaced-font" nil t)

(autoload 'lx/set-monospaced-font/decrease-font-size "lx-set-monospaced-font" nil t)

(register-definition-prefixes "lx-set-monospaced-font" '("lx/set-monospaced-font/"))

;;;***

;;;### (autoloads nil "mcp-ext" "mcp-ext.el" (0 0 0 0))
;;; Generated autoloads from mcp-ext.el

(autoload 'gptel-mcp-register-tool "mcp-ext" nil t)

(autoload 'mcp-hub-start "mcp-ext" nil t)

;;;***

;;;### (autoloads nil "mu4e-ext" "mu4e-ext.el" (0 0 0 0))
;;; Generated autoloads from mu4e-ext.el

(autoload 'lx/open-mail-custom-layout-or-mu4e-main "mu4e-ext" nil t)

;;;***

;;;### (autoloads nil "org-funcs" "org-funcs.el" (0 0 0 0))
;;; Generated autoloads from org-funcs.el

(autoload 'lx/open-org-calendar "org-funcs" nil t)

(autoload 'lx/org-refile "org-funcs" nil t)

(autoload 'lx/force-update-mu4e "mu4e-ext" nil t)

;;;***

;;;### (autoloads nil "org-jira-ext" "org-jira-ext.el" (0 0 0 0))
;;; Generated autoloads from org-jira-ext.el

(autoload 'org-jira-cleanup-get-issues-from-custom-jql "org-jira-ext" "\


\(fn ARG)" t)

(autoload 'org-jira-progress-issue-to-resolved "org-jira-ext" nil t)

;;;***

;;;### (autoloads nil "org-journal-find-today-entry" "org-journal-find-today-entry.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from org-journal-find-today-entry.el

(autoload 'org-journal-find-today-entry "org-journal-find-today-entry" nil t)

(autoload 'org-journal-find-today-entry-same-window "org-journal-find-today-entry" nil t)

(autoload 'org-journal-new-todo-entry "org-journal-find-today-entry" nil t)

;;;***

;;;### (autoloads nil "processes-ext" "processes-ext.el" (0 0 0 0))
;;; Generated autoloads from processes-ext.el

(autoload 'lx/kill-processes "processes-ext" "\


\(fn PROCESSES-EXT)" t)

(autoload 'lx/get-all-processes-except "processes-ext" "\


\(fn KEEP-PROCESS-NAMES)" t)

(autoload 'lx/kill-except-default-processes "processes-ext" nil t)

;;;***

;;;### (autoloads nil "projectile-ext" "projectile-ext.el" (0 0 0 0))
;;; Generated autoloads from projectile-ext.el

(autoload 'get-current-persp-project "projectile-ext")

(autoload 'projectile-project-alternate-buffer "projectile-ext")

(autoload 'projectile-project-switch-to-alternate-buffer "projectile-ext" nil t)

(autoload 'lx/find-or-create-projectile-snippet-file "projectile-ext" nil t)

(autoload 'lx/find-or-create-projectile-request-file "projectile-ext" nil t)

(autoload 'lx/find-or-create-projectile-snippet-org "projectile-ext" "\


\(fn IN-OTHER-WINDOW)" t)

(autoload 'lx/find-or-create-projectile-request-org "projectile-ext" "\


\(fn IN-OTHER-WINDOW)" t)

(autoload 'lx/find-or-create-projectile-sql-org "projectile-ext" "\


\(fn IN-OTHER-WINDOW)" t)

(autoload 'lx/find-or-create-projectile-alternate-org "projectile-ext" "\


\(fn IN-OTHER-WINDOW)" t)

(autoload 'projectile-find-file-in-pwd "projectile-ext" nil t)

(autoload 'lx/open-persp-project-file "projectile-ext" nil t)

(autoload 'lx/open-magit-toplevel-file "projectile-ext" nil t)

;;;***

;;;### (autoloads nil "projectile-shell-pop" "projectile-shell-pop.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from projectile-shell-pop.el

(autoload 'projectile-shell-pop "projectile-shell-pop" "\


\(fn PREFIX)" t)

;;;***

;;;### (autoloads nil "remove-empty-lines" "remove-empty-lines.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from remove-empty-lines.el

(autoload 'lx/remove-empty-lines "remove-empty-lines" "\
Remove empty lines

\(fn ARG)" t)

;;;***

;;;### (autoloads nil "ruby-ext" "ruby-ext.el" (0 0 0 0))
;;; Generated autoloads from ruby-ext.el

(autoload 'binding-pry-filter "ruby-ext" "\


\(fn TEXT)")

(autoload 'enh-ruby-toggle-block "ruby-ext" nil t)

(autoload 'current-line-has-pry-breakpoint-p "ruby-ext")

(autoload 'delete-pry-breakpoints "ruby-ext")

(autoload 'toggle-pry-breakpoint "ruby-ext" nil t)

(autoload 'cleanup-pry-breakpoints "ruby-ext" nil t)

(autoload 'lx/jump-to-code-at-point "ruby-ext" nil t)

(autoload 'lx/ruby-send-line "ruby-ext" nil t)

(autoload 'lx/ruby-send-line-and-go "ruby-ext" nil t)

(autoload 'lx/ruby-send-reload "ruby-ext" nil t)

(autoload 'lx/ruby-send-paragraph "ruby-ext" nil t)

(autoload 'lx/ruby-send-paragraph-and-go "ruby-ext" nil t)

(autoload 'lx/ruby-send-region "ruby-ext")

(autoload 'lx/ruby-send-region-and-go "ruby-ext")

(autoload 'lx/ruby-send-babel-block "ruby-ext" nil t)

(autoload 'lx/ruby-send-babel-block-and-go "ruby-ext" nil t)

(autoload 'lx/find-pry-ghostel-buffer "ruby-ext")

;;;***

;;;### (autoloads nil "save-scratch" "save-scratch.el" (0 0 0 0))
;;; Generated autoloads from save-scratch.el

(autoload 'lx/save-scratch "save-scratch" nil t)

;;;***

;;;### (autoloads nil "send-to-ghostel" "send-to-ghostel.el" (0 0 0 0))
;;; Generated autoloads from send-to-ghostel.el

(autoload 'lx/ghostel-send-line "send-to-ghostel" nil t)

(autoload 'lx/ghostel-send-line-and-go "send-to-ghostel" nil t)

(autoload 'lx/ghostel-send-paragraph "send-to-ghostel" nil t)

(autoload 'lx/ghostel-send-paragraph-and-go "send-to-ghostel" nil t)

(autoload 'lx/ghostel-send-region "send-to-ghostel" nil t)

(autoload 'lx/ghostel-send-region-and-go "send-to-ghostel" nil t)

(autoload 'lx/ghostel-send-babel-block "send-to-ghostel" nil t)

(autoload 'lx/ghostel-send-babel-block-and-go "send-to-ghostel" nil t)

(autoload 'lx/find-ghostel-buffer "send-to-ghostel")

(register-definition-prefixes "send-to-ghostel" '("send-to-ghostel-mode"))

;;;***

;;;### (autoloads nil "set-gh-profile-current-profile" "set-gh-profile-current-profile.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from set-gh-profile-current-profile.el

(autoload 'lx/set-gh-profile-current-profile "set-gh-profile-current-profile")

;;;***

;;;### (autoloads nil "set-last-dir-and-quit" "set-last-dir-and-quit.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from set-last-dir-and-quit.el

(autoload 'lx/set-last-dir-and-quit "set-last-dir-and-quit" nil t)

;;;***

;;;### (autoloads nil "sudo-save" "sudo-save.el" (0 0 0 0))
;;; Generated autoloads from sudo-save.el

(autoload 'sudo-save "sudo-save" nil t)

;;;***

;;;### (autoloads nil "switch-to-previous-persp" "switch-to-previous-persp.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from switch-to-previous-persp.el

(autoload 'lx/remember-previous-persp "switch-to-previous-persp" "\


\(fn &rest ARGS)")

(autoload 'lx/switch-to-previous-perp "switch-to-previous-persp" nil t)

;;;***

;;;### (autoloads nil "text" "text.el" (0 0 0 0))
;;; Generated autoloads from text.el

(autoload 'lx/cleanup-text-properties "text" nil t)

;;;***

;;;### (autoloads nil "term-funcs" "term-funcs.el" (0 0 0 0))
;;; Generated autoloads from term-funcs.el

(autoload 'lx/toggle-emacs-tmux "term-funcs" nil t)

(autoload 'lx/toggle-emacs-tmux-popup "term-funcs" nil t)

(autoload 'lx/toggle-project-tmux-session "term-funcs" nil t)

(autoload 'lx/toggle-project-tmux-session-popup "term-funcs" nil t)

(autoload 'lx/toggle-pry-window "term-funcs" nil t)

(autoload 'lx/split-right-and-ghostel "term-funcs" nil t)

(autoload 'lx/run-arql "term-funcs" nil t)

(autoload 'lx/run-jshell "term-funcs" nil t)

(autoload 'lx/run-arthas "term-funcs" nil t)

(autoload 'lx/run-alidash "term-funcs" nil t)

(autoload 'lx/run-flo "term-funcs" nil t)

(autoload 'lx/run-tuinnel "term-funcs" nil t)

(autoload 'lx/run-k9s "term-funcs" nil t)

(autoload 'lx/run-htop "term-funcs" nil t)

(autoload 'lx/run-ptpython "term-funcs" nil t)

(autoload 'lx/ssh-to-lx-sd "term-funcs" nil t)

(autoload 'lx/ssh-to-mini-ex "term-funcs" nil t)

(autoload 'lx/ssh-to-jicai-prod1 "term-funcs" nil t)

(autoload 'lx/ssh-to-jicai-prod2 "term-funcs" nil t)

(autoload 'lx/ssh-to-jicai-prod3 "term-funcs" nil t)

(autoload 'lx/ssh-to-jicai-uat "term-funcs" nil t)

(autoload 'lx/ssh-to-jicai-dev "term-funcs" nil t)

(autoload 'lx/ssh-to-donghe "term-funcs" nil t)

(autoload 'lx/ssh-to-donghe-hk01 "term-funcs" nil t)

(autoload 'lx/ssh-to-ueos-dev "term-funcs" nil t)

(autoload 'lx/ssh-to-manjaro-z4 "term-funcs" nil t)

(autoload 'lx/ssh-to-lx "term-funcs" nil t)

(autoload 'lx/vrl-jicai-dev "term-funcs" nil t)

(autoload 'lx/vrl-jicai-uat "term-funcs" nil t)

(autoload 'lx/vrl-jicai-prod "term-funcs" nil t)

(autoload 'lx/run-bandwhich "term-funcs" nil t)

(autoload 'lx/run-update-all "term-funcs" nil t)

(autoload 'lx/run-obsidian-sync "term-funcs" nil t)

(autoload 'lx/run-listening-ports "term-funcs" nil t)

(autoload 'lx/run-duf "term-funcs" nil t)

(autoload 'lx/run-lazyrsync "term-funcs" nil t)

(autoload 'lx/run-jira-cli "term-funcs" nil t)

(autoload 'lx/run-git-multi-status "term-funcs" nil t)

(autoload 'lx/run-git-multi-status-all "term-funcs" nil t)

(autoload 'lx/run-git-multi-branch "term-funcs" nil t)

(autoload 'lx/run-git-multi-pull "term-funcs" nil t)

(autoload 'lx/run-git-remote-branches "term-funcs" nil t)

(autoload 'lx/pop-to-arql-console "term-funcs" nil t)

(autoload 'lx/run-chatsh "term-funcs" nil t)

(autoload 'lx/run-jless "term-funcs" nil t)

(autoload 'lx/run-lnav "term-funcs" nil t)

;;;***

;;;### (autoloads nil "title-format" "title-format.el" (0 0 0 0))
;;; Generated autoloads from title-format.el

(autoload 'lx/layout-format-name "title-format" "\
Format the layout name given by NAME for display in mode-line.

\(fn NAME POS)")

(autoload 'lx/layouts-for-title-bar "title-format" "\
Return a one liner string containing all the layout names.")

(autoload 'lx/default-title-bar "title-format")

(autoload 'lx/toggle-title-format "title-format" nil t)

;;;***

;;;### (autoloads nil "toggle-global-mc-mode" "toggle-global-mc-mode.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from toggle-global-mc-mode.el

(autoload 'lx/toggle-global-evil-mc-mode "toggle-global-mc-mode" nil t)

(autoload 'lx/evil-mc-make-cursors-by-regexp "toggle-global-mc-mode" nil t)

(autoload 'lx/evil-mc-make-cursors-on-paragraph "toggle-global-mc-mode" nil t)

(autoload 'lx/evil-mc-make-cursors-on-region "toggle-global-mc-mode" nil t)

;;;***

;;;### (autoloads nil "toggle-global-syntax-check" "toggle-global-syntax-check.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from toggle-global-syntax-check.el

(autoload 'lx/toggle-global-syntax-check "toggle-global-syntax-check" nil t)

;;;***

;;;### (autoloads nil "toggles" "toggles.el" (0 0 0 0))
;;; Generated autoloads from toggles.el

(autoload 'org-toggle-org-modern-mode "toggles" nil t)

(autoload 'org-toggle-global-org-modern-mode "toggles" nil t)

;;;***

;;;### (autoloads nil "turn-off-sp-on-large-file" "turn-off-sp-on-large-file.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from turn-off-sp-on-large-file.el

(autoload 'turn-off-sp-on-large-file "turn-off-sp-on-large-file" nil t)

;;;***

;;;### (autoloads nil "update-tags" "update-tags.el" (0 0 0 0))
;;; Generated autoloads from update-tags.el

(autoload 'update-tags "update-tags" nil t)

;;;***

;;;### (autoloads nil "ui-funcs" "ui-funcs.el" (0 0 0 0))
;;; Generated autoloads from ui-funcs.el

(autoload 'lx/neotree-find-or-toggle "ui-funcs" nil t)

(autoload 'lx/neotree-toggle "ui-funcs" nil t)

(autoload 'lx/mouse-scroll-down "ui-funcs" nil t)

(autoload 'lx/mouse-scroll-up "ui-funcs" nil t)

(autoload 'lx/regenerate-tags "ui-funcs" nil t)

(autoload 'lx/enable-imenu-list "ui-funcs" nil t)

(autoload 'lx/toggle-annotate-mode "ui-funcs" nil t)

(autoload 'lx/set-default-font "ui-funcs" nil t)

(autoload 'lx/unhighlight-all "ui-funcs" nil t)

(autoload 'lx/dired-rpc-switches-fix "dired-rpc-switches-fix" nil t)

(autoload 'lx/agent-shell-select-session "agent-shell-enhanced" nil t)

(autoload 'lx/agent-shell-in-other-window "agent-shell-enhanced" nil t)

(autoload 'lx/proced-same-window "proced-enhanced-funcs" nil t)

;;;***

;;;### (autoloads nil "window-funcs" "window-funcs.el" (0 0 0 0))
;;; Generated autoloads from window-funcs.el

(autoload 'lx/delete-window-below "window-funcs" nil t)

(autoload 'lx/delete-window-above "window-funcs" nil t)

(autoload 'lx/delete-window-left "window-funcs" nil t)

(autoload 'lx/delete-window-right "window-funcs" nil t)

(autoload 'lx/popwin-rspec-buffer "window-funcs" nil t)

;;;***

;;;### (autoloads nil "xwidget-funcs" "xwidget-funcs.el" (0 0 0 0))
;;; Generated autoloads from xwidget-funcs.el

(autoload 'lx/xwidget-open-local-clash "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-remote-clash "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-openclash "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-github "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-gitlab "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-jenkins "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-jira "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-v2ex "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-emacs-china "xwidget-funcs" nil t)

(autoload 'lx/xwidget-open-twitter "xwidget-funcs" nil t)

;;;***

;;;### (autoloads nil "window-move" "window-move.el" (0 0 0 0))
;;; Generated autoloads from window-move.el

(autoload 'lx/window-move-very-top "window-move" nil t)

(autoload 'lx/window-move-very-bottom "window-move" nil t)

(autoload 'lx/window-move-far-left "window-move" nil t)

(autoload 'lx/window-move-far-right "window-move" nil t)

(autoload 'lx/def-window-frame-switch-function "window-move" "\


\(fn DIRECT-ARG)" nil t)

;;;***

;;;### (autoloads nil "xwidgets-integration" "xwidgets-integration.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from xwidgets-integration.el

(autoload 'xwidget-webkit-browse-mu4e-msg "xwidgets-integration" "\


\(fn URL &rest ARGS)")

(autoload 'my-mu4e-action-view-with-xwidget "xwidgets-integration" "\
View the body of the message inside xwidget-webkit.

\(fn MSG)")

;;;***

;;;### (autoloads nil "yank-to-end-of-line" "yank-to-end-of-line.el"
;;;;;;  (0 0 0 0))
;;; Generated autoloads from yank-to-end-of-line.el

(autoload 'yank-to-end-of-line "yank-to-end-of-line" nil t)

;;;***


;;;### (autoloads nil "lx/mark-and-yank-whole-buffer" "util-funcs.el" (0 0 0 0))
;;; Generated autoloads from autojump.el

(autoload 'lx/mark-and-yank-whole-buffer "util-funcs")

;;;***


;;;### (autoloads nil "lx/mark-and-delete-whole-buffer" "util-funcs.el" (0 0 0 0))
;;; Generated autoloads from autojump.el

(autoload 'lx/mark-and-delete-whole-buffer "util-funcs")


(autoload 'copilot-ensure-and-complete "copilot-enhanced")


(autoload 'lx/update-packages-and-restart "core"
  "Update Spacemacs packages without confirmation and restart Emacs only if updates were found." t)

;;;***


;;; End of scraped data

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; init.el ends here


(add-hook 'find-file-hook 'lx/autojump-add)
(add-hook 'dired-after-readin-hook 'lx/autojump-add)


;; Set the monospaced font size when mixed Chinese and English words, and if you use a computer with a retina display and a external display.
(setq lx/set-monospaced-font/font-names '("JetBrainsMono Nerd Font" "黑体-简"))
(setq lx/set-monospaced-font/iniital-font-size '(13 16))
(defvar lx/set-monospaced-font/font-size-options '((12 14)
                                                   (13 16)
                                                   (14 16)
                                                   (15 18)
                                                   (16 20)
                                                   (17 20)
                                                   (18 22)
                                                   (19 22)
                                                   (20 24)
                                                   (21 26)
                                                   (22 26)
                                                   (23 28)
                                                   (24 28)))

(defvar lx/set-monospaced-font/current-font-size lx/set-monospaced-font/iniital-font-size)
(setq lx/set-monospaced-font/min-font-size (car lx/set-monospaced-font/font-size-options))
(setq lx/set-monospaced-font/max-font-size (last lx/set-monospaced-font/font-size-options))

(setq mcp-started nil)

(defvar send-to-ghostel-mode-keymap (make-sparse-keymap))

(define-minor-mode send-to-ghostel-mode
  "Send to ghostel mode"
  :lighter " Send to ghostel"
  :keymap send-to-ghostel-mode-keymap
  :group 'send-to-ghostel-mode

  (spacemacs/set-leader-keys-for-minor-mode 'send-to-ghostel-mode
    "Sl" 'lx/ghostel-send-line
    "SL" 'lx/ghostel-send-line-and-go
    "Sr" 'lx/ghostel-send-region
    "SR" 'lx/ghostel-send-region-and-go
    "Sp" 'lx/ghostel-send-paragraph
    "SP" 'lx/ghostel-send-paragraph-and-go
    "Sb" 'lx/ghostel-send-babel-block
    "SB" 'lx/ghostel-send-babel-block-and-go
    "ss" 'ghostel-agent-send))


(add-hook 'persp-before-deactivate-functions 'lx/remember-previous-persp)


(lx/def-window-frame-switch-function 'up)
(lx/def-window-frame-switch-function 'down)
