;; Set the monospaced font size when mixed Chinese and English words, and if you use a computer with a retina display and a external display.
(setq lx/set-monospaced-font/font-names '("Source Code Pro" "黑体-简"))
(setq lx/set-monospaced-font/iniital-font-size '(14 16))
(defvar lx/set-monospaced-font/font-size-options '((14 16)
                                                   (13 16)
                                                   (14 16)
                                                   (15 18)
                                                   (16 20)
                                                   (17 20)
                                                   (18 22)
                                                   (19 22)
                                                   (20 24)
                                                   (21 26)
                                                   (22 26)
                                                   (23 28)
                                                   (24 28)))

(defvar lx/set-monospaced-font/current-font-size lx/set-monospaced-font/iniital-font-size)
(setq lx/set-monospaced-font/min-font-size (car lx/set-monospaced-font/font-size-options))
(setq lx/set-monospaced-font/max-font-size (last lx/set-monospaced-font/font-size-options))

(defun lx/set-monospaced-font (english chinese english-retina-size chinese-retina-size english-normal-size chinese-normal-size)
  (setq lx/set-monospaced-font/current-font-size (list english-retina-size chinese-retina-size))
  (when window-system
    (dolist (monitor-attrs (display-monitor-attributes-list))
      ;; (let* ((scale-factor (cdr (assoc 'backing-scale-factor monitor-attrs)))
      (let* ((scale-factor 2)
             (english-size (if (> scale-factor 1) english-retina-size english-normal-size))
             (chinese-size (if (> scale-factor 1) chinese-retina-size chinese-normal-size))
            (frames (cdr (assoc 'frames monitor-attrs))))
        (dolist (frame frames)
          (set-face-attribute 'default frame :font
                              (format   "%s:pixelsize=%d"  english english-size))
          (dolist (charset '(kana han symbol cjk-misc bopomofo))
            (set-fontset-font (frame-parameter frame 'font) charset
                              (font-spec :family chinese :size chinese-size) frame)))))))

(defun lx/set-monospaced-font/increase-font-size ()
  (interactive)
  (when (not (equal lx/set-monospaced-font/current-font-size lx/set-monospaced-font/max-font-size))
    (let* ((curr lx/set-monospaced-font/current-font-size)
           (idx (-elem-index lx/set-monospaced-font/current-font-size lx/set-monospaced-font/font-size-options))
           (next-idx (1+ idx))
           (next (nth next-idx lx/set-monospaced-font/font-size-options)))
    (apply 'lx/set-monospaced-font (append lx/set-monospaced-font/font-names next next)))))


(defun lx/set-monospaced-font/decrease-font-size ()
  (interactive)
  (when (not (equal lx/set-monospaced-font/current-font-size lx/set-monospaced-font/min-font-size))
    (let* ((curr lx/set-monospaced-font/current-font-size)
           (idx (-elem-index lx/set-monospaced-font/current-font-size lx/set-monospaced-font/font-size-options))
           (next-idx (1- idx))
           (next (nth next-idx lx/set-monospaced-font/font-size-options)))
      (apply 'lx/set-monospaced-font (append lx/set-monospaced-font/font-names next next)))))
