(defun projectile-shell-pop (prefix)
  (interactive "P")
  (if prefix
      (let* ((projectile-project-root (projectile-project-root))
             (index (or (gethash projectile-project-root projectile-term-index-hash-table)
                        (1+ (apply 'max 99 (hash-table-values projectile-term-index-hash-table))))))
        (switch-to-buffer (get-buffer (format "*vterm-%d*" index))))
    (if (string= "vterm-mode" major-mode)
        (shell-pop-out)
      (if (not (projectile-project-p))
          (spacemacs/shell-pop-vterm 0)
        (if (not (boundp 'projectile-term-index-hash-table)) (setq projectile-term-index-hash-table (make-hash-table :test 'equal)))
        (let* ((projectile-project-root (projectile-project-root))
               (index (or (gethash projectile-project-root projectile-term-index-hash-table)
                          (1+ (apply 'max 99 (hash-table-values projectile-term-index-hash-table)))))
               (shell-pop-autocd-to-working-dir nil))
          (puthash projectile-project-root index projectile-term-index-hash-table)
          (spacemacs/shell-pop-vterm index))))))
