(spacemacs|use-package-add-hook company
  :post-config
  (define-key company-active-map (kbd "C-r") 'helm-company)
  (push 'company-robe company-backends)
  ;; (add-to-list 'company-backends #'company-tabnine)
  (spacemacs|add-company-backends
    :backends company-indirect-sql-backend
    :modes sql-mode)
  (define-key company-mode-map (kbd "<backtab>") 'copilot-accept-completion)
  (define-key company-mode-map (kbd "M-f") 'lx/copilot-accept-or-forward-word)
  (define-key company-mode-map (kbd "C-n") 'lx/copilot-accept-or-next-line)
  (define-key company-active-map (kbd "C-l") 'yas/expand)
  (define-key company-active-map (kbd "C-y") '(lambda () (interactive) (company-abort) (call-interactively 'company-yasnippet)))
  (add-hook 'company-after-completion-hook '(lambda (&optional args) (copilot-clear-overlay)))

  )

(with-eval-after-load 'company-box
  (setq company-box-icons-all-the-icons
        `((Unknown . ,(all-the-icons-octicon "file-text" :height 0.8 :v-adjust -0.05))
          (Text . ,(all-the-icons-faicon "file-text-o" :height 0.8 :v-adjust -0.0575))
          (Method . ,(all-the-icons-faicon "cube" :height 0.8 :v-adjust -0.0575))
          (Function . ,(all-the-icons-faicon "cube" :height 0.8 :v-adjust -0.0575))
          (Constructor . ,(all-the-icons-faicon "cube" :height 0.8 :v-adjust -0.0575))
          (Field . ,(all-the-icons-faicon "tag" :height 0.8 :v-adjust -0.0575))
          (Variable . ,(all-the-icons-faicon "tag" :height 0.8 :v-adjust -0.0575))
          (Class . ,(all-the-icons-faicon "cog" :height 0.8 :v-adjust -0.0575))
          (Interface . ,(all-the-icons-faicon "cogs" :height 0.8 :v-adjust -0.0575))
          (Module . ,(all-the-icons-alltheicon "less" :height 0.8))
          (Property . ,(all-the-icons-faicon "wrench" :height 0.8 :v-adjust -0.0575))
          (Unit . ,(all-the-icons-faicon "tag" :height 0.8 :v-adjust -0.0575))
          (Value . ,(all-the-icons-faicon "tag" :height 0.8 :v-adjust -0.0575))
          (Enum . ,(all-the-icons-faicon "file-text-o" :height 0.8 :v-adjust -0.0575))
          (Keyword . ,(all-the-icons-material "format_align_center" :height 0.8 :v-adjust -0.225))
          (Snippet . ,(all-the-icons-material "content_paste" :height 0.8 :v-adjust -0.225))
          (Color . ,(all-the-icons-material "palette" :height 0.8 :v-adjust -0.225))
          (File . ,(all-the-icons-faicon "file" :height 0.8 :v-adjust -0.0575))
          (Reference . ,(all-the-icons-faicon "tag" :height 0.8 :v-adjust -0.0575))
          (Folder . ,(all-the-icons-faicon "folder" :height 0.8 :v-adjust -0.0575))
          (EnumMember . ,(all-the-icons-faicon "tag" :height 0.8 :v-adjust -0.0575))
          (Constant . ,(all-the-icons-faicon "tag" :height 0.8 :v-adjust -0.0575))
          (Struct . ,(all-the-icons-faicon "cog" :height 0.8 :v-adjust -0.0575))
          (Event . ,(all-the-icons-faicon "bolt" :height 0.8 :v-adjust -0.0575))
          (Operator . ,(all-the-icons-faicon "tag" :height 0.8 :v-adjust -0.0575))
          (TypeParameter . ,(all-the-icons-faicon "cog" :height 0.8 :v-adjust -0.0575))
          (Template . ,(all-the-icons-octicon "file-code" :height 0.8 :v-adjust -0.05)))))
