(with-eval-after-load 'ctable

  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "k" 'ctbl:navi-move-up)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "j" 'ctbl:navi-move-down)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "h" 'ctbl:navi-move-left)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "p" 'ctbl:navi-move-up)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "p" 'evil-start-next)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "q" 'bury-buffer)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "b" 'ctbl:navi-move-left)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "f" 'ctbl:navi-move-right)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "c" 'ctbl:navi-jump-to-column)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "e" 'ctbl:navi-move-right-most)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "a" 'ctbl:navi-move-left-most)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "0" 'ctbl:navi-move-left-most)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "$" 'ctbl:navi-move-right-most)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "g" #'(lambda () (interactive) (evil-goto-first-line 3)))
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "?" 'ctbl:describe-bindings)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings [mouse-1] 'ctbl:navi-on-click)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "C-m" 'ctbl:navi-on-click)
  (evilified-state-evilify-map ctbl:table-mode-map :mode ctbl:table-mode :bindings "RET" 'ctbl:navi-on-click)
  )
