(with-eval-after-load 'markdown-mode
  (spacemacs/set-leader-keys-for-major-mode 'markdown-mode "'" 'markdown-edit-code-block)
  (evil-define-key 'motion markdown-mode-map (kbd "C-i") 'markdown-cycle)
  (evil-define-key 'normal markdown-mode-map (kbd "C-i") 'markdown-cycle)
  (define-key markdown-mode-map (kbd "C-i") 'markdown-cycle)
  (define-key markdown-mode-map (kbd "M-h") nil)
  (define-key markdown-mode-map (kbd "M-j") nil)
  (define-key markdown-mode-map (kbd "M-k") nil)
  (define-key markdown-mode-map (kbd "M-l") nil)
  (define-key markdown-mode-map (kbd "M-H") nil)
  (define-key markdown-mode-map (kbd "M-J") nil)
  (define-key markdown-mode-map (kbd "M-K") nil)
  (define-key markdown-mode-map (kbd "M-L") nil)
  ;; (add-hook 'markdown-mode-hook #'turn-company-english-helper-on 100)
  )
