(with-eval-after-load 'xwidget
  (define-key xwidget-webkit-mode-map (kbd "s-f") 'xwwp-follow-link)
  (define-key xwidget-webkit-mode-map (kbd "s-c") 'xwidget-webkit-copy-selection-as-kill)
  (define-key xwidget-webkit-mode-map (kbd "y") 'xwidget-webkit-copy-selection-as-kill)
  (define-key xwidget-webkit-mode-map (kbd "s-W") '(lambda () (interactive) (let ((kill-buffer-query-functions nil)) (kill-buffer) (delete-window))))
  (define-key xwidget-webkit-mode-map (kbd "Q") '(lambda () (interactive) (let ((kill-buffer-query-functions nil)) (kill-buffer))))
  (define-key xwidget-webkit-mode-map (kbd "f") 'xwwp-follow-link)
  (define-key xwidget-webkit-mode-map (kbd "g") 'xwidget-webkit-scroll-top)
  (define-key xwidget-webkit-mode-map (kbd "G") 'xwidget-webkit-scroll-bottom)
  (define-key xwidget-webkit-mode-map (kbd "j") 'xwidget-webkit-scroll-up-line)
  (define-key xwidget-webkit-mode-map (kbd "k") 'xwidget-webkit-scroll-down-line)
  (define-key xwidget-webkit-mode-map (kbd "d") 'xwidget-webkit-scroll-up)
  (define-key xwidget-webkit-mode-map (kbd "u") 'xwidget-webkit-scroll-down)
  (define-key xwidget-webkit-mode-map (kbd "h") 'xwidget-webkit-back)
  (define-key xwidget-webkit-mode-map (kbd "l") 'xwidget-webkit-forward)
  (evil-define-key 'evilified xwidget-webkit-mode-map (kbd "g") 'xwidget-webkit-scroll-top)
  (evil-define-key 'evilified xwidget-webkit-mode-map (kbd "G") 'xwidget-webkit-scroll-bottom)
  (evil-define-key 'evilified xwidget-webkit-mode-map (kbd "j") 'xwidget-webkit-scroll-up-line)
  (evil-define-key 'evilified xwidget-webkit-mode-map (kbd "k") 'xwidget-webkit-scroll-down-line)
  (evil-define-key 'evilified xwidget-webkit-mode-map (kbd "h") 'xwidget-webkit-back)
  (evil-define-key 'evilified xwidget-webkit-mode-map (kbd "l") 'xwidget-webkit-forward)

  (evil-define-key 'visual xwidget-webkit-mode-map (kbd "y") 'xwidget-webkit-copy-selection-as-kill)
  (evil-define-key 'visual xwidget-webkit-mode-map (kbd "s-c") 'xwidget-webkit-copy-selection-as-kill)

  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "s-f") 'xwwp-follow-link)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "s-c") 'xwidget-webkit-copy-selection-as-kill)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "y") 'xwidget-webkit-copy-selection-as-kill)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "s-W") #'(lambda () (interactive) (let ((kill-buffer-query-functions nil)) (kill-buffer) (delete-window))))
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "Q") #'(lambda () (interactive) (let ((kill-buffer-query-functions nil)) (kill-buffer))))
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "f") 'xwwp-follow-link)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "g") 'xwidget-webkit-scroll-top)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "G") 'xwidget-webkit-scroll-bottom)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "j") 'xwidget-webkit-scroll-up-line)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map "k" 'xwidget-webkit-scroll-down-line)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "d") 'xwidget-webkit-scroll-up)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "u") 'xwidget-webkit-scroll-down)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "h") 'xwidget-webkit-back)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "l") 'xwidget-webkit-forward)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "=") 'xwidget-webkit-zoom-in)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "-") 'xwidget-webkit-zoom-out)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "r") 'xwidget-webkit-reload)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "w") 'xwidget-webkit-current-url)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "C-m") 'xwidget-webkit-insert-string)
  (evilified-state-evilify xwidget-webkit-mode xwidget-webkit-mode-map (kbd "a") 'xwidget-webkit-adjust-size-dispatch)
  )
