(advice-add 'spacemacs/set-state-faces :override (lambda ()
  (when (string= "spacemacs-dark" spacemacs--cur-theme)
    (face-spec-set 'enh-ruby-op-face '((t (:foreground "#b2b2b2"))))
    (face-spec-set 'enh-ruby-string-delimiter-face '((t (:foreground "#3c95d2"))))
    (face-spec-set 'linum '((t (:background "#292b2e" :foreground "#44505c"))))
    (face-spec-set 'mode-line '((t (:background "#222226" :foreground "#b2b2b2" :box (:line-width 1 :color "#5d4d7a") :overline nil :underline nil))))
    (face-spec-set 'mode-line-inactive '((t (:background "#292b2e" :foreground "#b2b2b2" :box (:line-width 1 :color "#5d4d7a") :overline nil :underline nil))))
    (face-spec-set 'diff-hl-change '((t (:background "#69B7F0" :foreground "#00629D"))))
    (face-spec-set 'diff-hl-delete '((t (:background "#FF6E64" :foreground "#990A1B"))))
    (face-spec-set 'diff-hl-insert '((t (:background "#B4C342" :foreground "#546E00"))))
    )
  (when (string= "solarized-light" spacemacs--cur-theme)
    (face-spec-set 'enh-ruby-op-face '((t (:foreground "#748488"))))
    (face-spec-set 'enh-ruby-string-delimiter-face '((t (:foreground "#b58901"))))
    (face-spec-set 'linum '((t (:background "#fdf6e4" :foreground "#93a1a1"))))
    (face-spec-set 'mode-line '((t (:background "#eee8d5" :foreground "#657b83" :box (:line-width 1 :color "#657b83") :overline nil :underline nil))))
    (face-spec-set 'mode-line-inactive '((t (:background "#fdf6e3" :foreground "#93a1a1" :box (:line-width 1 :color "#93a1a1") :overline nil :underline nil))))
    (face-spec-set 'diff-hl-change '((t (:background "#69B7F0" :foreground "#00629D"))))
    (face-spec-set 'diff-hl-delete '((t (:background "#FF6E64" :foreground "#990A1B"))))
    (face-spec-set 'diff-hl-insert '((t (:background "#B4C342" :foreground "#546E00"))))
    )

  (defvar spacemacs-evil-cursors '(("normal" "DarkGoldenrod2" box)
                                   ("insert" "chartreuse3" (bar . 2))
                                   ("emacs" "SkyBlue2" box)
                                   ("hybrid" "SkyBlue2" (bar . 2))
                                   ("replace" "chocolate" (hbar . 2))
                                   ("evilified" "LightGoldenrod3" box)
                                   ("visual" "gray" (hbar . 2))
                                   ("motion" "plum3" box)
                                   ("lisp" "HotPink1" box)
                                   ("iedit" "firebrick1" box)
                                   ("iedit-insert" "firebrick1" (bar . 2)))
    "Colors assigned to evil states with cursor definitions.")

  (cl-loop for (state color cursor) in spacemacs-evil-cursors
           do
           (eval `(face-spec-set ',(intern (format "spacemacs-%s-face" state))
                                 `((t (:background ,color
                                                   :foreground ,(face-background 'mode-line)
                                                   :box ,(face-attribute 'mode-line :box)
                                                   :inherit 'mode-line)))
                                 ))
           (set (intern (format "evil-%s-state-cursor" state))
                (list (when dotspacemacs-colorize-cursor-according-to-state color)
                      cursor)))
  (lx/set-monospaced-font "Source Code Pro" "STHeiti" 12 14 12 14)))
