;; -*- lexical-binding: t; -*-

(global-unset-key (kbd "s-q"))
(global-unset-key (kbd "<f10>"))
(global-set-key (kbd "s-l") 'evil-avy-goto-line)
(global-set-key (kbd "<s-S-return>") 'spacemacs/toggle-maximize-buffer)
(global-set-key (kbd "s-t") 'split-window-right-and-focus)
(global-set-key (kbd "s-T") 'split-window-below-and-focus)
(global-set-key (kbd "s-O") 'helm-projectile-find-file)
(global-set-key (kbd "s-R") 'revert-buffer)
;; (global-set-key (kbd "s-O") 'spacemacs/helm-find-files-recursively)
(global-set-key (kbd "s-o") 'lx/helm-find-project-files)
(global-set-key (kbd "s-f") 'spacemacs/helm-find-files)
(global-set-key (kbd "M-s-f") 'helm-find)
(global-set-key (kbd "C-x C-f") 'spacemacs/helm-find-files)
(global-set-key (kbd "s-F") 'helm-locate)
(global-set-key (kbd "s-B") 'lx/switch-to-buffer)
(global-set-key (kbd "s-b") 'lx/switch-to-project-or-all-buffer)
(global-set-key (kbd "s-L") 'spacemacs/helm-perspectives)
(global-set-key (kbd "M-.") 'company-complete)
(global-set-key (kbd "s-;") #'lx/toggle-emacs-tmux)
(global-set-key (kbd "s-:") #'lx/toggle-project-tmux-session)
(global-set-key (kbd "s-'") #'lx/toggle-emacs-tmux-popup)
(global-set-key (kbd "s-\"") #'lx/toggle-project-tmux-session-popup)

(global-set-key (kbd "s-r s-;") #'lx/toggle-pry-window)
(global-set-key (kbd "s-[") 'previous-buffer)
(global-set-key (kbd "s-]") 'next-buffer)
(global-set-key (kbd "s-/") 'evilnc-comment-or-uncomment-lines)
(global-set-key (kbd "s-\\") 'lx/switch-to-previous-perp)
(global-set-key (kbd "s-M-'") #'lx/split-right-and-ghostel)

(global-set-key (kbd "s-n") #'lx/new-untitled-buffer)
(global-set-key (kbd "s-N") #'lx/new-untitled-buffer-same-window)
(global-set-key (kbd "s-w") 'lx/delete-window-or-bury-buffer)
(global-set-key (kbd "s-W") #'lx/kill-buffer-and-delete-window)
(global-set-key (kbd "s-D") 'spacemacs/kill-this-buffer)
(global-set-key (kbd "M-s-n") #'lx/make-frame)
(global-set-key (kbd "M-s-w") 'delete-frame)
;; (global-set-key (kbd "s-C") 'bzg-big-fringe-mode)
(global-set-key (kbd "s-g") #'lx/magit-status-smart)
;; (global-set-key (kbd "s-r s-a") #'lx/pop-to-arql-console)
(global-set-key (kbd "s-r q") #'lx/run-arql)
(global-set-key (kbd "s-r j") #'lx/run-jshell)
(global-set-key (kbd "s-r a") #'lx/run-arthas)
(global-set-key (kbd "s-r d") #'lx/run-alidash)
(global-set-key (kbd "s-r f") #'lx/run-flo)
(global-set-key (kbd "s-r t") #'lx/run-tuinnel)
(global-set-key (kbd "s-r k") #'lx/run-k9s)
(global-set-key (kbd "s-r h") #'lx/run-htop)
(global-set-key (kbd "s-r 0") #'lx/ssh-to-lx-sd)
(global-set-key (kbd "s-r 1") #'lx/ssh-to-jicai-prod1)
(global-set-key (kbd "s-r 2") #'lx/ssh-to-jicai-prod2)
(global-set-key (kbd "s-r 3") #'lx/ssh-to-jicai-prod3)
(global-set-key (kbd "s-r 4") #'lx/ssh-to-jicai-dev)
(global-set-key (kbd "s-r 5") #'lx/ssh-to-jicai-uat)
(global-set-key (kbd "s-r 6") #'lx/ssh-to-ueos-dev)
(global-set-key (kbd "s-r 8") #'lx/ssh-to-manjaro-z4)
(global-set-key (kbd "s-r 9") #'lx/ssh-to-lx)
(global-set-key (kbd "s-r l 1") #'lx/vrl-jicai-dev)
(global-set-key (kbd "s-r l 2") #'lx/vrl-jicai-uat)
(global-set-key (kbd "s-r l 3") #'lx/vrl-jicai-prod)
(global-set-key (kbd "s-r p") #'helm-ghostel-prize)
(global-set-key (kbd "s-r s-p") #'lx/run-ptpython)
(global-set-key (kbd "s-r s-r s-p") #'ghostel-mitmproxy-transparent-proxy)
(global-set-key (kbd "s-r s-r p") #'ghostel-mitmproxy-local-proxy)
(global-set-key (kbd "s-r s-s") #'helm-zsh-ghostel-ssh)
(global-set-key (kbd "s-r s-q") #'helm-pry-ghostel-arql)
(global-set-key (kbd "s-r s-l") #'helm-ghostel-vrl)
(global-set-key (kbd "s-r m m") #'helm-ghostel-maven-deploy)
(global-set-key (kbd "s-r m d") #'helm-ghostel-maven-deploy)
(global-set-key (kbd "s-r m c") #'helm-ghostel-maven-deploy-current-artifact)
(global-set-key (kbd "s-r m p") #'helm-ghostel-maven-deploy-parent-artifact)
(global-set-key (kbd "s-r m t") #'helm-ghostel-maven-deps-tree)
(global-set-key (kbd "s-r m r") #'helm-ghostel-maven-deps-resolve)
(global-set-key (kbd "s-r m u") #'ghostel-maven-update-local-artifact)
(global-set-key (kbd "s-r m k") #'ghostel-maven-kill-local-artifact)
(global-set-key (kbd "s-r s-j") #'helm-ghostel-jenkins)
(global-set-key (kbd "s-r s-r bw") #'lx/run-bandwhich)
(global-set-key (kbd "s-r s-r ua") #'lx/run-update-all)
(global-set-key (kbd "s-r s-r os") #'lx/run-obsidian-sync)
(global-set-key (kbd "s-r s-r lp") #'lx/run-listening-ports)
(global-set-key (kbd "s-r s-r df") #'lx/run-duf)
(global-set-key (kbd "s-r s-r j") #'lx/run-jira-cli)
(global-set-key (kbd "s-r s-r gs") #'lx/run-git-multi-status)
(global-set-key (kbd "s-r s-r gb") #'lx/run-git-multi-branch)
(global-set-key (kbd "s-r s-r gl") #'lx/run-git-multi-pull)
(global-set-key (kbd "s-r s-r ga") #'lx/run-git-remote-branches)
(global-set-key (kbd "s-r s-r ad") #'arthas-class-reload-docker)
(global-set-key (kbd "s-r s-r ak") #'arthas-class-reload-k8s)
(global-set-key (kbd "s-r s-a") #'ghostel-agent-run-claude)
(global-set-key (kbd "s-r s-c") #'ghostel-agent-run-cursor)
(global-set-key (kbd "s-r s-g") #'ghostel-agent-run-agy)
(global-set-key (kbd "s-r s-o") #'ghostel-agent-run-opencode)
(global-set-key (kbd "s-r s-t") #'ghostel-agent-run-aliyun-token-plan-claude)
(global-set-key (kbd "s-r s-d") #'ghostel-agent-run-deepseek-claude)
(global-set-key (kbd "s-r b") #'helm-ghostel-buffers)

(global-set-key (kbd "s-u") 'universal-argument)
(define-key universal-argument-map (kbd "s-u") 'universal-argument-more)
(global-set-key [M-s-tab] #'spacemacs/alternate-buffer-in-persp)
;; (global-set-key [M-S-tab] #'projectile-project-switch-to-alternate-buffer)
(global-set-key [M-S-tab] #'lx/switch-to-project-3rd-buffer)

(global-set-key (kbd "C-g") 'lx/keyboard-quit)
(global-set-key [M-tab] 'spacemacs/alternate-buffer)
(global-set-key (kbd "C-M-i") 'spacemacs/alternate-buffer)
(unless (display-graphic-p) (global-set-key (kbd "C-M-i") 'spacemacs/alternate-buffer) (global-set-key (kbd "<f10>") 'spacemacs/alternate-buffer))
(global-set-key (kbd "<f5>") #'lx/regenerate-tags)
(global-set-key (kbd "M-@") 'set-mark-command)
(global-set-key (kbd "s-m") 'set-mark-command)
(global-set-key (kbd "C-x s-m") 'pop-global-mark)
(global-set-key (kbd "<f1>") #'lx/neotree-find-or-toggle)
(global-set-key (kbd "<S-f1>") #'lx/neotree-toggle)
(global-set-key [mouse-4] #'lx/mouse-scroll-down)
(global-set-key [mouse-5] #'lx/mouse-scroll-up)

(global-set-key (kbd "M-h") #'evil-window-left)
(global-set-key (kbd "M-l") #'evil-window-right)
(global-set-key (kbd "M-j") #'lx/window-down-fallback-to-switch-frame)
(global-set-key (kbd "M-k") #'lx/window-up-fallback-to-switch-frame)
(global-set-key (kbd "M-H") #'lx/window-move-far-left)
(global-set-key (kbd "M-J") #'lx/window-move-very-bottom)
(global-set-key (kbd "M-K") #'lx/window-move-very-top)
(global-set-key (kbd "M-L") #'lx/window-move-far-right)

(global-set-key (kbd "s-M") #'helm-mu)

(global-set-key (kbd "s-0") 'spacemacs/persp-switch-to-0)
(global-set-key (kbd "s-1") 'spacemacs/persp-switch-to-1)
(global-set-key (kbd "s-2") 'spacemacs/persp-switch-to-2)
(global-set-key (kbd "s-3") 'spacemacs/persp-switch-to-3)
(global-set-key (kbd "s-4") 'spacemacs/persp-switch-to-4)
(global-set-key (kbd "s-5") 'spacemacs/persp-switch-to-5)
(global-set-key (kbd "s-6") 'spacemacs/persp-switch-to-6)
(global-set-key (kbd "s-7") 'spacemacs/persp-switch-to-7)
(global-set-key (kbd "s-8") 'spacemacs/persp-switch-to-8)
(global-set-key (kbd "s-9") 'spacemacs/persp-switch-to-9)
(global-set-key (kbd "s-{") 'persp-prev)
(global-set-key (kbd "s-}") 'persp-next)

(global-set-key (kbd "M-0") 'winum-select-window-0)
(global-set-key (kbd "M-1") 'winum-select-window-1)
(global-set-key (kbd "M-2") 'winum-select-window-2)
(global-set-key (kbd "M-3") 'winum-select-window-3)
(global-set-key (kbd "M-4") 'winum-select-window-4)
(global-set-key (kbd "M-5") 'winum-select-window-5)
(global-set-key (kbd "M-6") 'winum-select-window-6)
(global-set-key (kbd "M-7") 'winum-select-window-7)
(global-set-key (kbd "M-8") 'winum-select-window-8)
(global-set-key (kbd "M-9") 'winum-select-window-9)

(global-set-key (kbd "C-M-s-)") 'winum-select-window-0)
(global-set-key (kbd "C-M-s-!") 'winum-select-window-1)
(global-set-key (kbd "C-M-s-@") 'winum-select-window-2)
(global-set-key (kbd "C-M-s-#") 'winum-select-window-3)
(global-set-key (kbd "C-M-s-$") 'winum-select-window-4)
(global-set-key (kbd "C-M-s-%") 'winum-select-window-5)
(global-set-key (kbd "C-M-s-^") 'winum-select-window-6)
(global-set-key (kbd "C-M-s-&") 'winum-select-window-7)
(global-set-key (kbd "C-M-s-*") 'winum-select-window-8)
(global-set-key (kbd "C-M-s-(") 'winum-select-window-9)

(global-set-key (kbd "<f12>") #'imenu-list-smart-toggle)

(global-set-key (kbd "M-`") 'neotree-show)

(global-set-key (kbd (if (display-graphic-p) "<C-return>" "C-RET")) #'spacemacs/jump-to-definition)
(global-set-key (kbd (if (display-graphic-p) "<s-return>" "s-RET")) #'spacemacs/jump-to-definition-other-window)

(global-set-key (kbd "s-j") #'lx/evil-next-10-lines)
(global-set-key (kbd "s-k") #'lx/evil-previous-10-lines)

;; s-i
(global-set-key (kbd "s-i s-0") 'lx/find-or-create-projectile-alternate-org)
(global-set-key (kbd "s-i s-o") 'lx/find-or-create-projectile-snippet-org)
(global-set-key (kbd "s-i s-p") 'lx/find-or-create-projectile-request-org)
(global-set-key (kbd "s-i s-q") 'lx/find-or-create-projectile-sql-org)
(global-set-key (kbd "s-i s-m") 'lx/toggle-global-evil-mc-mode)
(global-set-key (kbd "s-i s-r") 'lx/evil-mc-make-cursors-by-regexp)
(global-set-key (kbd "s-i p") 'lx/evil-mc-make-cursors-on-paragraph)
(global-set-key (kbd "s-i r") 'lx/evil-mc-make-cursors-on-region)
(global-set-key (kbd "s-i s-t") 'insert-translated-name-replace)
(global-set-key (kbd "s-i s-c") 'org-capture)
(global-set-key (kbd "s-i s-b") 'helm-filtered-bookmarks)
(global-set-key (kbd "s-i s-i") 'spacemacs/helm-jump-in-buffer)
(global-set-key (kbd "s-i a") 'claude-code-ide-menu)
(global-set-key (kbd "s-i s-a") 'claude-code-ide-menu)

;; s-p
(global-unset-key (kbd "s-p"))

(global-set-key (kbd "s-p s-w") #'helm-autojump)
(global-set-key (kbd "s-p s-p") 'helm-projectile-switch-project)
(global-set-key (kbd "s-p s-r") 'projectile-dired)
(global-set-key (kbd "s-p s-s") 'lx/helm-persp-replace-project)
(global-set-key (kbd "s-p s-a") 'spacemacs/helm-persp-switch-project)
(global-set-key (kbd "s-p s-o") 'lx/helm-projectile-open-projects)
(global-set-key (kbd "s-p s-u") 'lx/helm-projectile-other-open-projects)
(global-set-key (kbd "s-p s-l") 'spacemacs/helm-perspectives)
(global-set-key (kbd "s-p s-t") #'lx/open-persp-project-file)
(global-set-key (kbd "s-e") #'lx/open-persp-project-file)
(global-set-key (kbd "s-p s-g") #'lx/open-magit-toplevel-file)

(global-set-key (kbd "s-<backspace>") 'kill-whole-line)

(global-set-key (kbd "s-s") #'lx/save-buffer)

(global-set-key (kbd "M-s-b") 'helm-cwd-buffers)
(global-set-key (kbd "s-V") 'lx/indent-paste)

(global-set-key (kbd "s-i s-j s-j") #'org-jira-cleanup-get-issues-from-custom-jql)
(global-set-key (kbd "s-i s-j j") #'org-jira-get-issues-from-custom-jql)
(global-set-key (kbd "s-i s-j s-p") #'org-jira-progress-issue-to-resolved)
(global-set-key (kbd "s-i s-j s-b") #'org-jira-browse-issue)
(global-set-key (kbd "s-i s-j s-u") #'org-jira-update-issue)
(global-set-key (kbd "s-i s-j s-r") #'org-jira-refresh-issue)
(global-set-key (kbd "s-i s-j s-a") #'org-jira-assign-issue)
(global-set-key (kbd "s-i s-j p") #'org-jira-progress-issue)
(global-set-key (kbd "s-i s-j ib") #'org-jira-browse-issue)
(global-set-key (kbd "s-i s-j ig") #'org-jira-get-issues)
(global-set-key (kbd "s-i s-j ih") #'org-jira-get-issues-headonly)
(global-set-key (kbd "s-i s-j if") #'org-jira-get-issues-from-filter-headonly)
(global-set-key (kbd "s-i s-j iu") #'org-jira-update-issue)
(global-set-key (kbd "s-i s-j iw") #'org-jira-progress-issue)
(global-set-key (kbd "s-i s-j ir") #'org-jira-refresh-issue)
(global-set-key (kbd "s-i s-j ic") #'org-jira-create-issue)
(global-set-key (kbd "s-i s-j iy") #'org-jira-copy-current-issue-key)
(global-set-key (kbd "s-i s-j sc") #'org-jira-create-subtask)
(global-set-key (kbd "s-i s-j sg") #'org-jira-get-subtasks)
(global-set-key (kbd "s-i s-j cu") #'org-jira-update-comment)
(global-set-key (kbd "s-i s-j tj") #'org-jira-todo-to-jira)

(global-set-key (kbd "s-i TAB") #'lx/enable-imenu-list)

(global-set-key (kbd "s-?") #'lx/clojure-repl)

(global-set-key (kbd "s-=") #'lx/set-monospaced-font/increase-font-size)
(global-set-key (kbd "s--") #'lx/set-monospaced-font/decrease-font-size)

(global-set-key (kbd "TAB") #'lx/tab)
(global-set-key (kbd "M-\\") 'copilot-ensure-and-complete)
(global-set-key (kbd "M-]") 'copilot-next-completion)
;; (global-set-key (kbd "M-f") 'lx/copilot-accept-or-forward-word)
;; (global-set-key (kbd "C-n") 'lx/copilot-accept-or-next-line)
;; (global-set-key (kbd "M-[") 'copilot-previous-completion) ;; Comment out this kbd due to confliction with S-TAB in terminal
;; (global-set-key (kbd "<backtab>") #'copilot-accept-completion)
(global-set-key (kbd "M-?") 'all-buffer-completion)
(global-set-key (kbd "s-H") 'dash-at-point)
(global-set-key (kbd "s-I") 'gptel-menu)

;; Customization of command-a
(global-unset-key (kbd-mac-command "a"))
(global-set-key (kbd "s-a s-a") 'mark-whole-buffer)
(global-set-key (kbd "s-a s-c") #'lx/mark-and-yank-whole-buffer)
(global-set-key (kbd "s-a s-d") #'lx/mark-and-delete-whole-buffer)
(global-set-key (kbd "s-a j o") 'org-journal-find-today-entry)
(global-set-key (kbd "s-a j j") 'org-journal-new-todo-entry)
(global-set-key (kbd "s-a j J") 'org-journal-new-entry)
(global-set-key (kbd "s-a c") 'claude-code-ide-menu)

(global-unset-key (kbd "s-y"))
(global-set-key (kbd "s-y s-y") 'lx/agent-shell-in-other-window)
(global-set-key (kbd "s-y y") 'agent-shell)
(global-set-key (kbd "s-a y") 'agent-shell)
(global-set-key (kbd "s-y b") 'lx/agent-shell-select-session)
(global-set-key (kbd "s-y s f") 'agent-shell-send-current-file)
(global-set-key (kbd "s-y s s") 'agent-shell-send-dwim)
(global-set-key (kbd "s-y s F") 'agent-shell-send-other-file)
(global-set-key (kbd "s-y s r") 'agent-shell-send-region)
(global-set-key (kbd "s-y @") 'agent-shell-send-file)
(global-set-key (kbd "s-a q") 'clutch-query-console)

(global-set-key (kbd "s-&") #'bury-buffer)
